# =====================================================================
# SPELLING MAPPING
# =====================================================================
SPELLING_MAPPING = {
    # Hier können Wortkorrekturen eingetragen werden
}

# =====================================================================
# MEDICAL MAPPINGS
# =====================================================================

# WUNDTYP MAPPING
WUNDTYP_GT_MAPPING = {
    # z.B. "Postoperative Wunde abdominal": ["Postoperative Wunde"]
    "Ulcus": ["Ulkus"],
    "Dekubtis": ["Dekubitus"],
    "Decubitus": ["Dekubitus"],
    "Ulcera": ["Ulkus"],
    "Ulcerationen": ["Ulkus"],
    "Ulcus decubitus": ["Dekubitus"],
    "Ulcus Dekubitus": ["Dekubitus"],
    "Ulcus dekubitus": ["Dekubitus"],

    # ---- Ulkus ----
    "zirkuläres Ulcus Unterschenkel (vermutlich Mischulcus)": ["Ulkus"],
    "Ulcus am Fussrücken": ["Ulkus"],
    "semizirkuläres Ulcus re Fuß": ["Ulkus"],
    "Ulcus, bei vermutetem Diabetes": ["Ulkus"],
    "Ulcus mit Stauung": ["Ulkus"],
    "Teils nekrotisches Ulcus an der linken Ferse.\nplantares Ulcus belegt mit Infektionszeichen": ["Ulkus"],
    "laterales Ulcus linker Fuß": ["Ulkus"],
    "Taschenbildendes Ulcus am linken Fußrücken": ["Ulkus"],
    "Fersenulcus / eventuell Mischulcus": ["Ulkus"],
    "Oberflächliches Ulcus (diffuse Defekte)": ["Ulkus"],
    "fibrinbelegtes Ulcus": ["Ulkus"],
    "Fibrinbelegtes Ulcus": ["Ulkus"],
    "Ulcus nach Meshgraft (zumindest lässt die Struktur darauf schließen), eventuell ist die Struktur aber einer Unterdrucktherapie geschuldet": ["Ulkus"],
    "belegter Ulcus": ["Ulkus"],
    "Oberflächliches Ulcus": ["Ulkus"],
    "Fibringbelegtes Ulcus": ["Ulkus"],
    "oberflächliches Ulcus": ["Ulkus"],
    "vermutlich Mischulcus am rechten Bein, höhe der Knöchel.\nSemizirkulär": ["Mischulkus"],
    "Infiziertes Ulcus mit freiliegender Sehne": ["Ulkus"],
    "Ulcus mit scheinender Hypergranulation oberhalb der Achillessehne": ["Ulkus"],
    "tiefes Ulcus im Fersenbereich": ["Ulkus"],
    "Ulcus nach Stich": ["Ulkus"],
    "Plantares Ulcus linker Fuß, Ursachen Klärung notwendig, bei Diabetiker Prüfung ob Neuropathisch oder Angiopathische Ursache": ["Ulkus"],
    "könnte arterieller Ulcus oder diabetischer Ulcus ( Angiopathie) auf Grund der Mangeldurchblutung  sein.": ["Ulkus"],
    "Ulcus unklarer Genese, könnte Venös oder arteriell oder mixum sein.\nBeachte kleine Nekrose an der Ferse plantar": ["Ulkus"],
    "Ulcus auf Grund von Mangelernährung des Gewebes, Druckschäden in Kombination mit Gefäßschäden": ["Ulkus"],
    "Ulcus unklarer Genese, könnte diabet. Ulcus sein, möglich ebenso durch traumatologische Ursachen": ["Ulkus"],
    "Ulcus lokal abgegrenzt. belegt könnte ebenso nekrotisch sein": ["Ulkus"],
    "Ulcus Ursache nicht genau definierbar": ["Ulkus"],
    "Ulcus. Ursache klären sollte es ein diabet. Fuß sein dann Prüfung ob angiopathisch oder neuropathisch,\nDruckentlastung und Ursachenbeseitigung.": ["Ulkus"],
    "Ulcus, durch die Mangelernährung ( keine Durchblutung) im Wundgebiet  könnte es sich um einen Dekubitus oder ulcus cruris handeln.": ["Ulkus"],
    "Ulcus unklarer Genese": ["Ulkus"],
    "Ulcus am Unterschenkel medial": ["Ulkus"],
    "Ulcus unbekannter Herkunft, könnte traumatologisch bedingte Wunde sein, durch die Wunde bei unsachgemäßer Versorgung entstehen ulcerationen ebenfalls, nicht immer Krankheitsbedingt": ["Ulkus"],
    "Ulcus, Lokalisation am Bein nicht genau definierbar": ["Ulkus"],
    "Ulcus unklarer Genese am Bein genaue Lokalisation nicht beurteilbar": ["Ulkus"],
    "Ulcus an der Achillessehne": ["Ulkus"],

    # ---- Ulkus cruris ----
    "Ulcus cruris venosum": ["Ulkus cruris venosum"],
    "Ulcus cruris li lateraler Malleolus": ["Ulkus cruris"],
    "Ulcus cruris": ["Ulkus cruris"],
    "Ulcus cruris /  Gravitationsulcus: Ulcus cruris venosum": ["Ulkus cruris venosum"],
    "schwere Nekrose am Fuß rechts lateral und plantar, offene Geschwüre über den Malleolen lateral\ndeutet auf arterielles Ulcus hin": ["Ulkus cruris arteriosum"],
    "Ulcus cruris möglich arteriell oder mixtum": ["Ulkus cruris"],
    "Ulcus cruris  unklarer Ursache": ["Ulkus cruris"],
    "Ulcus / warsch. Ulcus cruris, Ursache nicht klar, muss bestimmt werden": ["Ulkus cruris"],


    # ---- Ulkus ----
    "diffuse fibrinbelegte und teils infizierte Ulzera am rechten Fuß": ["Ulkus"],
    "semizirkuläres Ulcus": ["Ulkus"],
    "Ulcera rechter Fuß. könnte ursächlich diabetischer Fuß sein ( Neuropathie, Angiopathie) oder arterielles ulcus schäden auf Grund fehlender Durchblutung": ["Ulkus"],
    "schwere Ulzerationen am Fuß- mehrere offene Stellen, freiliegende Sehen, teilweise nekrotisch, belegt": ["Ulkus"],
    "superinfizierte Ulcration am rechen Fuß offene Ulcera": ["Ulkus"],
    "Ulcerationen bedingt durch Vaskulitis- Form der rheumatischen Erkrankung ( Autoimmunerkrankung)": ["Ulkus"],
    "offene ulcera": ["Ulkus"],

    # ---- Dekubitus ----
    "nekrotischer Defekt / Dekubitus": ["Dekubitus"],
    "nekrotischer Dekubitus li Ferse": ["Dekubitus"],
    "Dekubitus, vermutlich am Außenknöchel": ["Dekubitus"],
    "Fersendekubitus": ["Dekubitus"],
    "Dekubitus an der Ferse": ["Dekubitus"],
    "Dekubitus mit Nekrose": ["Dekubitus"],
    "tiefer Dekubitus": ["Dekubitus"],
    "Dekubitus mit Taschenbildung": ["Dekubitus"],
    "Dekubtis im Sakralbereich, großflächig": ["Dekubitus"],
    "oberflächlicher Dekubitus ( 2 Stück)": ["Dekubitus"],

    "Ulcus decubitus": ["Dekubitus"],
    "massives Ulcus dekubitus": ["Dekubitus"],
    "Ulcus Dekubitus": ["Dekubitus"],
    "Ulkus an der Ferse, warsch. Dekubitus nach EPUAP  Stadium 3": ["Dekubitus"],
    "Ulcus Dekubitus nach Epuap Grad 2 bis 3": ["Dekubitus"],
    "Ulcus dekubitus Ferse,  Stadium 3 / 4": ["Dekubitus"],
    "Ulcus decubitus Nach Epuap Grad 2 bis 3": ["Dekubitus"],
    "Dekubitus sacralbereich": ["Dekubitus"],
    "Dekubitus epuap Stadium 3 / 4": ["Dekubitus"],
    "Ulcus Dekubitus Epuap Grad 3 / 4": ["Dekubitus"],
    "Ulcus dekubitus": ["Dekubitus"],
    "Dekubitus Grad 2 oder 3 nach EPUAP.\nNicht genau zu definieren, ob sich Unterminierungen vorhanden sind.": ["Dekubitus"],
    "Ulkus Dekubitus am Os sacrum  nach Epuap Grad 2 / 3": ["Dekubitus"],
    "Ulcus Dekubitus Bereich OS Sacrum": ["Dekubitus"],

    # ── Verbrennung ──
    "Verbrennungswunde 1. bis 2. Grades": ["Verbrennungswunde"],
    "Verbrennung 2. Grades am Bein": ["Verbrennungswunde"],
    "Verbrennung Grad 1 bis 2 am rechten Fuß": ["Verbrennungswunde"],
    "Verbrennung 2 und 3 Grades nach 9 er Regel etwa 9 % Körperoberfläche": ["Verbrennungswunde"],
    "Verbrennungswunde am Arm Grad 2": ["Verbrennungswunde"],
    "traumatologische Wunde ( thermische Schädigung / Verbrennung 3. und 4. Grades": ["Verbrennungswunde"],
    "Verbrennung 2. und teilweise 3. Grades Oberfläche ca 9 %": ["Verbrennungswunde"],

    # ── Nekrose ──
    "mumifizierte Zehen (D4 und D5), gleichzeitig Nekrose an der rechten Ferse": ["Nekrose"],
    "nekrotischen Wunden am Fuß": ["Nekrose"],
    "siehe oben": ["Nekrose"],

    # ---- Diabetisches Fußulkus ----
    "könnte diabetischer ulcus sein auf grund einer neuropathie": ["Diabetisches Fußulkus"],
    "könnte ein diabetischer Fuß sein, Ulcus  nicht möglich,\ntraumatologische Indikation ebenso nicht ausgeschlossen": ["Diabetisches Fußulkus"],
    "Ulcus auf Grund von Mangeldurchblutung. Könnte diabetischer Fuß sein / angiopathisch bedingt.": ["Diabetisches Fußulkus"],

    # ── Sonstige ──
    "Platzbauch nach möglichem chirurgischen Eingriff": ["Platzbauch"],
    "möglicherweise ein feuchtes Gangrän": ["Ischämisches Fußulkus (Gangrän)"],
    "Postoperative Wunde abdominal": ["Postoperative Wunde"],
    "infantiles Hämangiom,": ["Hämangiom"],

    # LLM
    # ---- Dekubitus ----
    "Dekubitus (Druckulkus)": ["Dekubitus"],
    "Dekubitus": ["Dekubitus"],
    "Dekubitus (Fersenulkus)": ["Dekubitus"],
    "Dekubitalulkus (Druckulcus) Ferse": ["Dekubitus"],
    "Druckulzer (Ferse/Fußulkus)": ["Dekubitus"],
    "Dekubitus (druckbedingtes Ulkus) an der Ferse": ["Dekubitus"],
    "Dekubitus (Druckulkus) Ferse": ["Dekubitus"],
    "Dekubitalulkus (Ferse)": ["Dekubitus"],
    "Dekubitalulkus (Druckulkus)": ["Dekubitus"],
    "Dekubitus (Druckulkus) der Ferse": ["Dekubitus"],
    "Dekubitalulkus (Druckulcus) an der Ferse": ["Dekubitus"],
    "Dekubitalulkus (Druckulkus) an der Ferse": ["Dekubitus"],
    "Dekubitus (Druckulzera)": ["Dekubitus"],

    # ---- Ulkus cruris ----
    "Ulcus cruris (vermutlich venös)": ["Ulkus cruris venosum"],
    "Ulcus cruris (wahrscheinlich venös)": ["Ulkus cruris venosum"],
    "Ulcus cruris": ["Ulkus cruris"],
    "Ulcus cruris (vermutlich venös), oberflächliche flächige Ulzeration": ["Ulkus cruris venosum","Ulkus"],

    "Ulcus cruris venosum (Verdacht)": ["Ulkus cruris venosum"],
    "Ulcus cruris (vermutlich venös, Bildbeurteilung)": ["Ulkus cruris venosum"],
    "Ulcus cruris (chronisch, Ätiologie unklar)": ["Ulkus cruris"],
    "Ulcus cruris (vermutet, chronische Unterschenkelwunde)": ["Ulkus cruris"],
    "Ulcus cruris (vermutet venös)": ["Ulkus cruris venosum"],
    "Ulcus cruris venosum (vermutet)": ["Ulkus cruris venosum"],
    "Ulcus cruris (wahrscheinlich venös), klein/oberflächlich": ["Ulkus cruris venosum"],
    "Ulcus cruris (Verdacht anhand Bild)": ["Ulkus cruris"],
    "Ulcus cruris (unklare Ätiologie)": ["Ulkus cruris"],
    "Ulcus cruris (vermutlich venös), chronische Wunde": ["Ulkus cruris venosum"],

    # ---- Ulkus ----
    "Traumatische/chronische Wunde (Fußulkus unklarer Genese)": ["Ulkus"],
    "Chronisches Fußulkus (mehrere Ulzerationen)": ["Ulkus"],
    "Traumatische/infizierte Ulzeration (kleines Ulkus)": ["Ulkus"],
    "Ulzeration, unklare Genese (oberflächlich, mit Nekrose/Fibrin)": ["Ulkus"],
    "Nekrotische Ulzeration (unklare Genese, möglich druck-/ischämiebedingt)": ["Ulkus"],

    # ---- Ulkus ----
    "Mehrere Ulzera am Fuß; Ätiologie im Bild nicht sicher (druck-/ischämisch möglich)": ["Ulkus"],
    "Mehrere nekrotisch-belegte Ulzera am Fuß (druck-/ischämieassoziiert möglich)": ["Ulkus"],
    "Multiple chronische Ulzera am Fuß (nur Bildbeurteilung)": ["Ulkus"],

    # ---- Diabetisches Fußulkus ----
    "Diabetisches Fußulkus (mehrere flache Ulzera)": ["Diabetisches Fußulkus"],
    "Plantare Fußulzeration (vermutet neuropathisch/diabetisches Fußulkus)": ["Diabetisches Fußulkus"],
    "Plantare Fußulzera, wahrscheinliches diabetisches/neuropathisches Fußulkus": ["Diabetisches Fußulkus"],

    # ---- Ischämisch / Nekrose ----
    "Ischämische, nekrotische Wunde (arterielles Ulcus möglich)": ["Ischämisches Fußulkus (Gangrän)"],
    "Nekrotische Fußwunde (z. B. Ulcus/Gangrän des Vorfußes)": ["Ischämisches Fußulkus (Gangrän)"],

    # ---- Verbrennung ----
    "Oberflächliche thermische Verletzung/Verbrennung (grad 2a) der Hand": ["Verbrennungswunde"],
    "Verbrennung (thermische Verletzung), flächig": ["Verbrennungswunde"],
    "Thermische Verletzung (Verbrennung/Verbrühung 2. Grades, bullös)": ["Verbrennungswunde"],
    "Thermische Verletzung (Verbrennung Grad 2b, Blasenbildung)": ["Verbrennungswunde"],

    # ---- Postoperative Wunde ----
    "Postoperative Wunde (dehiszient, sekundär heilend)": ["Postoperative Wunde"],
    "Postoperative Wunde (Spalthautentnahmestelle)": ["Postoperative Wunde"],
    "Postoperative/traumatische sekundär heilende Wunde": ["Postoperative Wunde","Traumatische Wunde"],
    "Traumatische oder postoperativ sekundär heilende Wunde": ["Postoperative Wunde","Traumatische Wunde"],

    # ---- Sonstige ----
    "Großflächige traumatische/sekundär heilende Wunde": ["Traumatische Wunde"],
    "Kleiner Abszess/Sinusöffnung (infizierte oberflächliche Hautläsion)": ["Abszess"],

    # ---- 2-Stage CoT LLM Mappings ----
    'Postoperative Wunde (Wunddehiszenz) nahe Stoma': ['Postoperative Wunde'],
    'Oberflächliches Ulkus am Unterschenkel; Ätiologie unklar (bildbasierter Befund)': ['Ulkus cruris'],
    'Hautulzeration (unklare Genese), zwei benachbarte Ulzera': ['Ulkus'],
    'Verbrennung (thermische Verletzung), großflächige Weichteilläsion': ['Verbrennungswunde'],
    'Verbrennungswunde (blasig, oberflächlich partiell)': ['Verbrennungswunde'],
    'Ulcus cruris, flächige oberflächliche Ulzeration': ['Ulkus cruris'],
    'Verbrennung (bullös, partielle Hautschädigung)': ['Verbrennungswunde'],
    'Nekrotisches Fußulkus (mehrere Läsionen)': ['Ulkus'],
    'Fußulkus (ausgedehnter, nekrotischer Defekt)': ['Ulkus'],
    'Druckulcus am Fuß (mehrere Ulzera)': ['Dekubitus'],
    'Ulcus cruris venosum (venös-typisch)': ['Ulkus cruris venosum'],
    'Ulkus': ['Ulkus'],
    'Mehrere Ulzera am lateralen Fuß mit Nekrose und Fibrinbelag': ['Ulkus'],
    'Fußulkus (mehrere oberflächliche Ulzera, Ätiologie unklar)': ['Ulkus'],
    'Mehrere oberflächliche Ulzera/Erosionen am Fuß (multifokal)': ['Ulkus'],
    'Fußulkus (Ätiologie unklar)': ['Ulkus'],
    'Druckulkus am Fuß (druck-/neuropathisch möglich)': ['Dekubitus'],
    'Druckulcus (Zehenulkus)': ['Dekubitus'],
    'Gangränöse, nekrotische Fußwunde (Ulkus)': ['Ischämisches Fußulkus (Gangrän)'],
    'Dekubitus (Ferse)': ['Dekubitus'],
    'Infizierte Hautläsion / kleiner Abszess': ['Abszess'],
    'Plantare Ulzeration (druckbedingt/neuropathisch, vereinbar mit diabetischem Fußulkus)': ['Diabetisches Fußulkus'],
    'Ulkus am Fußrücken (unklare Genese)': ['Ulkus'],
    'Plantarer Druckulkus des Vorfußes (vereinbar mit diabetischem Fußulkus), multiple Ulcera': ['Diabetisches Fußulkus'],
    'Dekubitus (Fersendruckulkus)': ['Dekubitus'],
    'Nekrotische Hautläsion / Ulkus': ['Ulkus'],
    'Ulcus cruris (Unterschenkelulkus)': ['Ulkus cruris'],
    'Ulkus/Weichteildefekt mit Fibrinbelag (Ätiologie anhand Bild nicht sicher bestimmbar)': ['Ulkus'],
    'Ulkus cruris': ['Ulkus cruris'],
    'Ulcus cruris (Beinulkus), Ätiologie unklar': ['Ulkus cruris'],
    'Ulcus cruris (oberflächlich)': ['Ulkus cruris'],
    'Ulcus cruris (oberflächliches Unterschenkelulkus)': ['Ulkus cruris'],
    'Ulkus cutis, Ätiologie unklar (aus Bild allein nicht bestimmbar)': ['Ulkus'],
    'Ulkus der Haut (Genese unklar, Bildbefund)': ['Ulkus'],
    'Ulcus cruris (bildbasiert; Ätiologie nicht sicher)': ['Ulkus cruris'],
    'Hautulkus (unklare Ätiologie)': ['Ulkus'],
    'Ulkus cruris venosum': ['Ulkus cruris venosum'],
    'Ulcus cruris (ausgedehntes Unterschenkelulkus)': ['Ulkus cruris'],
    'Ulcus cruris (stark exsudierend, fibrinbelegt)': ['Ulkus cruris'],
    'Oberflächliches Ulkus am Unterschenkel': ['Ulkus'],
    'Ulkus am Unterschenkel (Ätiologie unklar)': ['Ulkus'],
    'Dekubitus (Druckulcus an der Ferse)': ['Dekubitus'],
    'Dekubitus (Druckulkus der Ferse)': ['Dekubitus'],
    'Pilonidalsinus (Sinus pilonidalis)': ['Sinus pilonidalis'],
    'Dekubitus (mehrere Ulzera)': ['Dekubitus'],

    # ---- Few-Shot LLM Mappings ----
    # Dekubitus
    "Dekubitus (Druckulcus)": ["Dekubitus"],
    "Dekubitus (Druckulcus) an der Ferse": ["Dekubitus"],
    "Dekubitus (Druckulkus) mit Nekrosen": ["Dekubitus"],
    "Dekubitus (Druckulkus), tiefer Defekt": ["Dekubitus"],
    "Dekubitus (Druckulzera), multipel": ["Dekubitus"],
    "Dekubitus (sakral/paraglutäal)": ["Dekubitus"],
    "Druckulcus (Dekubitus)": ["Dekubitus"],
    "Druckulcus (Ferse)": ["Dekubitus"],
    "Druckulcus an der Ferse": ["Dekubitus"],
    "Druckulcus der Ferse (Fersendekubitus) mit trockener Eschar": ["Dekubitus"],
    "Druckulkus / Ulkus an der Ferse": ["Dekubitus", "Ulkus"],
    "Druckulkus der Ferse (Fersenulkus)": ["Dekubitus"],
    "Druckulzeration / Fersenulkus": ["Dekubitus", "Ulkus"],

    # Ulkus cruris
    "Ulcus cruris (V. a. venös)": ["Ulkus cruris venosum"],
    "Ulcus cruris (chronisches Unterschenkelulkus)": ["Ulkus cruris"],
    "Ulcus cruris (infiziert, stark exsudierend)": ["Ulkus cruris"],
    "Ulcus cruris (oberflächlich), unklare Ätiologie": ["Ulkus cruris"],
    "Ulcus cruris (venös verdächtig) – großes, oberflächliches Ulkus": ["Ulkus cruris venosum"],
    "Ulcus cruris (venös vermutet)": ["Ulkus cruris venosum"],
    "Ulcus cruris (vermutet), flächige oberflächliche Erosion": ["Ulkus cruris"],
    "Ulcus cruris (vermutet), großflächig mit Belägen": ["Ulkus cruris"],
    "Ulcus cruris (vermutet), oberflächliche chronische Wunde": ["Ulkus cruris"],
    "Ulcus cruris (Ätiologie unklar)": ["Ulkus cruris"],
    "Ulcus cruris, multiple oberflächliche Ulzera": ["Ulkus cruris"],
    "Ulkus cruris (nekrotisch-belegt)": ["Ulkus cruris"],
    "Ulkus am Unterschenkel (Ätiologie unklar, Bild legt venöses Ulkus nahe)": ["Ulkus cruris venosum"],

    # Ulkus / Fußulkus
    "Chronisches Ulkus am Unterschenkel (oberflächlich)": ["Ulkus"],
    "Fußulkus (V. a. neuropathisch/diabetisch), druckbedingt": ["Ulkus", "Diabetisches Fußulkus"],
    "Großflächige oberflächliche Ulzeration": ["Ulkus"],
    "Mehrere oberflächliche Hautdefekte/Ulzera am Fußrücken": ["Ulkus"],
    "Mehrfache Fußulzera, teils nekrotisch": ["Ulkus"],
    "Multiple Ulcera am lateralen Fuß": ["Ulkus"],
    "Multiple oberflächliche Ulcera am Fuß": ["Ulkus"],
    "Nekrotisch belegtes Fußulkus (Ätiologie unklar)": ["Ulkus"],
    "Nekrotische Ulzeration": ["Ulkus"],
    "Oberflächliche Ulzeration/traumatische Wunde mit Nekrose": ["Ulkus", "Traumatische Wunde"],
    "Plantarer Fußulkus": ["Ulkus"],
    "Ulkus (chronische Wunde), Ätiologie unklar": ["Ulkus"],
    "Ulkus (oberflächliche chronische Wunde)": ["Ulkus"],
    "Ulkus (Ätiologie unklar)": ["Ulkus"],
    "Ulkus am Fuß (druck-/schuhbedingt möglich)": ["Ulkus"],
    "Ulkus am Fußrücken": ["Ulkus"],
    "Ulkus am Unterschenkel (Ätiologie unklar), infektverdächtig": ["Ulkus"],
    "Ulkus am lateralen Fußrand (mehrere Läsionen) mit Belägen/Nekrose": ["Ulkus"],

    # Ischämisch / Nekrose
    "Ausgedehnte nekrotische Wunde am Fuß (gangränöser Aspekt)": ["Ischämisches Fußulkus (Gangrän)"],
    "Ischämischer Fußulkus / nekrotische Wunde (Gangränverdacht)": ["Ischämisches Fußulkus (Gangrän)"],

    # Verbrennung
    "Thermische Verletzung – Verbrennung 2. Grades mit Blasenbildung": ["Verbrennungswunde"],
    "Verbrennung/Verbrühung Grad 2 (oberflächlich-partiell), großflächig": ["Verbrennungswunde"],

    # Postoperative / Traumatische / Sonstige
    "Großflächige, oberflächliche traumatische Wunde / möglich Spalthaut-Entnahmestelle": ["Traumatische Wunde", "Postoperative Wunde"],
    "Kleines Ulkus/Abszessöffnung (möglicher Fistelgang)": ["Ulkus", "Abszess"],
    "Postoperative Wunddehiszenz, infiziert": ["Postoperative Wunde"],
    "Reibungsblase / oberflächliche Hautläsion": ["Blasenbildung"],
    "Traumatische Weichteilverletzung mit Blasenbildung/Hämatom am Fuß (geschlossene Hautschädigung)": ["Traumatische Wunde"],
    "Traumatische/thermische Hautläsion mit ausgedehnter Nekrose": ["Traumatische Wunde", "Verbrennungswunde"],
}

# WUNDGRUND MAPPING
WUNDGRUND_GT_MAPPING = {
    # z.B. "Granulation": ["Granulation"]
    "nekrotisch": ["Nekrose"],
    "Fibrinbelegt": ["Fibrinbelag"],
    "Sauber, bis auf die aufgetragene Salbe": ["Sauber"],
    "Fibrinbelegte Wunde": ["Fibrinbelag"],
    "nekrotisch belegt": ["Nekrose", "Fibrinbelag"],
    "Fibringbelegt mit durschscheinendem Granulationsgewebe": ["Fibrinbelag", "Granulation"],
    "Mischuntergrund. Fibrinbelag, nekrotisch, teils mit Granulationsinseln": ["Mischuntergrund", "Fibrinbelag", "Nekrose", "Granulation"],
    "teilweise fibrinbelegt mit einzelnen Granulationsinseln": ["Fibrinbelag", "Granulation"],
    "sauberer Wundgrund mit Inseln von Granulation": ["Sauber", "Granulation"],
    "Fibrinbelegt mit einzelnen Granulationsinseln": ["Fibrinbelag", "Granulation"],
    "Fibrinbelegtes tiefes Ulcus": ["Fibrinbelag", "Ulzeration"],
    "Fibrinbelegt bei Wundrandepithelisierung": ["Fibrinbelag", "Wundrandepithelisierung"],
    "belegt mit Hypergranulation": ["Hypergranulation"],
    "Fibrinbelegte Wundverhältnisse": ["Fibrinbelag"],
    "Fibrinbelegt, zerklüftet": ["Fibrinbelag","Zerklüftet"],
    "Sauberer Wundgrund mit kleinen Fibrininseln": ["Sauber", "Fibrinbelag"],

    "belegt, teilweise nekrotisch": ["Belag", "Nekrose"],
    "stark infiziert, massiv belegt": ["Infektion", "Belag"],
    "verbrannte  Epidermis": ["Verbrennung"],
    "belegt, nekrotisch": ["Belag", "Nekrose"],
    "massive großflächige Verbrennung teilweise 4. Grades, je mehr es vom Wundzentrum nach außen geht werden Verbrennungen 3 7 2. und 1. Grades sichtbar. Nach der 9 er regel könnten hier bis zu 9 % der Körperoberfläche geschädigt sein": ["Verbrennung"],
    "Verbrennungen, Blasenbildung, offene Wunden keine verbrannten Sehnen / Knochen  epidermis geschädigt": ["Verbrennung", "Blasenbildung"],
    "stark belgtes Ulcus, teilweise einzelne Granulationsinseln,": ["Belag", "Granulation"],
    "hämatös": ["Hämatom"],
    "Fußwunde: Nekrotisch  Unterschenkelwunde fibrinös belegt,": ["Nekrose", "Fibrinbelag"],
    "sehr ausgeprägte massive Nekrose, teilweise frei liegende Strukturen, blutig seröses Exsudat": ["Nekrose", "Freiliegende Strukturen", "Exsudat"],
    "belegte Wunde, teilweise infiziert": ["Belag", "Infektion"],
    "Nekrotische und fibrinös belegte Wunde- auf Grund der Mazeration nach plantar hin könnte mäßige Exsudation auftreten. Wundinfektion möglich": ["Nekrose", "Fibrinbelag", "Mazeration"],
    "fibrinös belegt, zum Teil mit Granulationsinseln, teilweise freiliegende Sehnen.\nNekrose plantar wandständig trocken": ["Fibrinbelag", "Granulation", "Freiliegende Sehnen", "Nekrose"],
    "mehrere Stadien zu erkennen, nekrotisch, belegt, teilweise granuliert": ["Nekrose", "Belag", "Granulation"],
    "Nekrotisch und durch Infektion belegt, Wunde bildet Geruch, Frage der Keimbestimmung wichtig, Wundabstrich notwendig,": ["Nekrose", "Infektion"],
    "teilweise nekrotisch, belegt": ["Nekrose", "Belag"],
    "offenen stelle entzündet. belegt, nekrotisch, geschlossene stelle nekrotisch": ["Entzündung", "Belag", "Nekrose"],
    "wandständige Nekrose, Prüfung, ob Knochen / Sehnen betroffen sind. Unbedingt chirurgisch intervenieren.\nDruckentlastung essentiell.": ["Nekrose"],
    "fibrinös belegt, unterminierte Wundränder siehe punktierte Markierung\nEventuelle freie Sehnen": ["Fibrinbelag", "Unterminierung","Freiliegende Sehnen"],
    "freiliegende Sehnen Strang 5, freiliegende Knochen,\nteilweise nekrotisch": ["Freiliegende Sehnen", "Freiliegende Knochen", "Nekrose"],
    "großes Ulcus: belegt, teilweise nekrotisch\nZehe: trockene Nekrose- bitte nicht durch autolytisches Débridement anfeuchten. Zeh fällt irgendwann ab, da die Durchblutung massiv gestört ist. Gefäßstatus prüfen und gfls. sanieren": ["Belag", "Nekrose"],
    "Kleine Nekrose oberhalb des großen offenen Ulcus, muss mit versorgt werden\nsonstig massiv belegt, Nekrosenbildung bei Nichtbehandlung wahrscheinlich. Prüfung ob knöcherne Strukturen / Sehnen betroffen sind": ["Nekrose", "Belag"],
    "belegt, teilweise nekrotisch, teilweise überschießende Granulation": ["Belag", "Nekrose", "Hypergranulation"],
    "stark belegt, neben Fibrin könnte es sich auch um feuchte, wandständige Nekrosen handeln": ["Fibrinbelag"],
    "Granulation und Beläge gleichzeitig": ["Granulation", "Belag"],
    "belegt, mäßige Exsudation Infektion möglich": ["Belag", "Exsudat"],
    "leichte Granulation, belegt mit Fibrin, 2 Inseln Beurteilung hier schwer, da nicht genau zu erkennen sind, ob es ich um Nekrosen handelt.": ["Granulation", "Fibrinbelag"],
    "belegt, hypergranulation": ["Belag", "Hypergranulation"],
    "nekrotisch und fibrinös belegt": ["Nekrose", "Fibrinbelag"],
    "belegt, teilweise kleine Nekrosen, könnte infiziert sein": ["Belag", "Nekrose"],
    "kleinere Nekrosen, belegt": ["Nekrose", "Belag"],
    "belegt, teilweise nekrotisch könnte infiziert sein": ["Belag", "Nekrose"],
    "grünlich belegt, deutet auf Infektion hin, Nekrosen am  Wundgrund belegt": ["Belag", "Infektion", "Nekrose"],
    "stark belegte, super infizierte Wunde, teilweise freiliegende Strukturen,\nNekrosen.": ["Belag", "Infektion", "Freiliegende Strukturen", "Nekrose"],
    "stark geschädigt, nekrotisch, fibrinös belegt, freiliegende Sehnen / Knochen": ["Nekrose", "Fibrinbelag", "Freiliegende Sehnen", "Freiliegende Knochen"],
    "Granulationsgewebe, teilweise fibrinös belegt, Biofilm": ["Granulation", "Fibrinbelag", "Biofilm"],
    "belegt, fibrinös, nekrotisch": ["Fibrinbelag", "Nekrose"],
    "Granulationsinseln, fibrinös belegt": ["Granulation", "Fibrinbelag"],
    "belegt, teilweise kleine Nekrosen, könnte infiziert sein, belegt": ["Belag", "Nekrose"],
    "belegt, teilweise kleine Nekrosen freiliegende Sehne sichtbar": ["Belag", "Nekrose", "Freiliegende Sehnen"],
    "tiefer Dekubitus Wundgrund belegt, Taschenbildung teilweise nekrotisch": ["Belag", "Taschenbildung", "Nekrose"],
    "feuchte Nekrose,": ["Nekrose"],
    "nekrotisch, wandständige Nekrosen": ["Nekrose"],
    "nekrotisch, feuchte nekrose": ["Nekrose"],
    "fleischige Wunde mit Taschenbildung nach Feststellung der Ausdehnung": ["Granulation", "Taschenbildung"],
    "gerötet, stark geschädigt, teilweise nekrotisch belegt": ["Rötung", "Nekrose", "Belag"],

    # ---- 2-Stage CoT Wundgrund Mappings ----
    'Ausgedehnte gelblich-fibrinöse Beläge mit schwarz-braunen Nekrosen, dazwischen rötliche granulierende Areale; feucht-glänzend.': ['Fibrinbelag', 'Nekrose', 'Rötung', 'Granulation'],
    'Ausgedehnte schwarz-braune Nekrose/Eschar mit feucht-glänzender Oberfläche, teils fibrinös belegt; keine Granulation sichtbar.': ['Nekrose', 'Fibrinbelag'],
    'Feucht glänzender, teils gelblich fibrinös belegter Wundgrund mit fragiler Granulation, oberflächlich, keine erkennbaren Taschen.': ['Fibrinbelag', 'Granulation'],
    'Feucht-glänzender Wundgrund mit flächigen, gelblich-weißen fibrinösen Belägen/Slough und vereinzelten rötlichen Granulationsinseln; keine schwarze Nekrose erkennbar; keine freiliegenden Sehnen/Knochen.': ['Fibrinbelag', 'Granulation'],
    'Feuchtes, gut durchblutetes granulierendes Wundbett mit kleinen, fest anhaftenden fibrinösen Inseln/Belägen; kein nekrotisches Gewebe sichtbar.': ['Granulation', 'Fibrinbelag'],
    'Feuchtes, teils granulierendes Wundbett mit ausgeprägten gelb-weißlichen Fibrinbelägen; keine trockene Nekrose erkennbar.': ['Granulation', 'Fibrinbelag'],
    'Fibrinös-gelblicher Belag mit Inseln rötlicher Granulation; feucht, keine trockene Nekrose sichtbar.': ['Fibrinbelag', 'Rötung', 'Granulation'],
    'Flaches Ulkus mit gelblich-fibrinösen Belägen und Anteilen von Granulationsgewebe; feucht.': ['Ulzeration', 'Fibrinbelag', 'Granulation'],
    'Flaches, irreguläres Ulkus mit gelblich-fibrinösen Belägen und Anteilen von Granulationsgewebe; feucht.': ['Ulzeration', 'Fibrinbelag', 'Granulation'],
    'Flaches, ovales Ulkus mit überwiegend gelblich-beigem Fibrinbelag; feucht glänzend; keine schwarzen Nekrosen und keine freiliegenden tiefen Strukturen sichtbar.': ['Ulzeration', 'Fibrinbelag'],
    'Flächendeckende, zähe gelblich-weiße Fibrinbeläge/Slough (~80%) mit geringen granulierenden Inseln; feucht; keine schwarze Nekrose; unregelmäßige Wundtiefe.': ['Fibrinbelag', 'Granulation'],
    'Flächig erythematös-erosiv, teils mit weißlich-schuppigen Auflagerungen; kein nekrotisches Gewebe erkennbar; feucht-glänzend; mäßige Exsudation.': ['Rötung', 'Exsudat'],
    'Gelb-beiger, feuchter fibrinöser Belag/flächiger Slough, kaum Granulation sichtbar.': ['Fibrinbelag'],
    'Gelb-ockerfarbener, fest anhaftender Fibrin-/Nekrosebelag mit zentral dunklen (schwarz-braunen) Nekroseinseln; keine sichtbare Granulation; Oberfläche teils krustös, teils feucht glänzend.': ['Fibrinbelag', 'Nekrose'],
    'Gelb‑bräunlicher Fibrinbelag mit zentralen schwarz‑nekrotischen Arealen; kaum/keine sichtbare Granulation.': ['Fibrinbelag', 'Nekrose'],
    'Gelblich-beiger, feuchter Fibrinbelag/Slough (~70%) mit randständiger rötlicher Granulation (~30%); keine schwarze Nekrose sichtbar.': ['Fibrinbelag', 'Rötung', 'Granulation'],
    'Gelblich-fibrinös belegter, feucht-glänzender Wundgrund mit teils rötlichen Arealen; kein trockener Nekroseanteil sichtbar.': ['Fibrinbelag', 'Rötung'],
    'Gelblich-weißer, zäher fibrinöser Belag mit wenigen punktförmigen Blutungen; feucht, vereinzelte rötliche Areale.': ['Fibrinbelag', 'Rötung'],
    'Gemischt: überwiegend rote Granulation mit teils gelblich-fibrinösen Belägen; feuchter Wundgrund.': ['Rötung', 'Granulation', 'Fibrinbelag'],
    'Gemischter Wundgrund mit gelblichen fibrinösen Belägen/Slough und rötlichem Granulationsgewebe; feucht, mäßige Tiefe; kein freiliegender Knochen sichtbar.': ['Fibrinbelag', 'Rötung', 'Granulation'],
    'Gemischtes Wundbett mit schwarzen nekrotischen Arealen und gelb-grauem Fibrinbelag; zentral rötliches, feuchtes Granulationsgewebe; tiefe Ulzeration mit möglicher Unterminierung.': ['Nekrose', 'Fibrinbelag', 'Rötung', 'Granulation', 'Ulzeration', 'Unterminierung'],
    'Granulierender Wundgrund mit ausgeprägten gelblichen fibrinösen Belägen/Slough, teils adhärent; vereinzelt dunklere nekrotische Areale distal.': ['Granulation', 'Fibrinbelag', 'Nekrose'],
    'Großflächig gelb‑grünlicher, dicker Fibrin-/Slough-Belag, feucht und glänzend; am unteren Rand schwarz‑braune nekrotische/krustige Areale; nur wenige rötliche Granulationsinseln sichtbar; keine freiliegenden Strukturen (Knochen/Sehnen) erkennbar.': ['Fibrinbelag', 'Nekrose', 'Granulation'],
    'Großflächig nekrotisch mit schwarz-braunen Escharen; darüber ausgedehnter gelb-grünlicher fibrinöser Belag/Slough, feucht-glänzend; keine sichtbare Granulation oder Epithelisierung.': ['Nekrose', 'Fibrinbelag'],
    'Großflächiger gelb‑grünlicher Fibrinbelag/Slough mit einzelnen nekrotischen Arealen distal; feucht, kaum sichtbare Granulation.': ['Fibrinbelag', 'Nekrose'],
    'Großflächiger, feucht glänzender Wundgrund mit hell- bis dunkelroter Granulation; multiple gelblich‑weiße Fibrinbeläge/Slough-Inseln; unregelmäßige Oberfläche; keine trockene Nekrose sichtbar.': ['Granulation', 'Fibrinbelag'],
    'Großflächiges, feuchtes Wundbett mit dicken gelblich-grünlichen Fibrinbelägen/Slough; stellenweise rötliche Granulationsinseln; keine schwarze Trockennekrose erkennbar.': ['Fibrinbelag', 'Granulation'],
    'Großes rundes Ulkus mit überwiegend gelblich-weißem Fibrin-/Schleimhautbelag, zentral teils rötliche Granulationsinseln; randständig trockene nekrotische Krusten; feucht-glänzend; kein freiliegender Knochen oder Sehne sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Granulation', 'Nekrose'],
    'Hauptläsion: flaches, ovales Ulkus mit gelblich-beigem fibrinösem Belag, randständig teils rötlich, feucht glänzend; keine schwarze Nekrose, feuchtem Wundbett. Zweite kleinere, oberflächliche Läsion lateral mit rötlichem, keine sichtbaren tieferen Strukturen.': ['Ulzeration', 'Fibrinbelag', 'Rötung'],
    'Kavitäre Ulzeration mit überwiegend gelblich-cremigem fibrinösem Belag/Slough; stellenweise rötliche Granulationsinseln an der Innenwand; feucht mit dickflüssigem Exsudat; keine freiliegenden Knochen oder Sehnen sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Granulation', 'Exsudat'],
    'Kleines rundes Ulkus mit gelblich-fibrinösem Belag; kein freiliegendes tieferes Gewebe sichtbar.': ['Ulzeration', 'Fibrinbelag'],
    'Kleines, ovales Ulkus mit gelblich-fibrinösem Belag; feucht, keine freiliegenden Strukturen sichtbar.': ['Ulzeration', 'Fibrinbelag'],
    'Kleine punktförmige Öffnungen/Pusteln mit serösem bis seropurulentem Exsudat, umgebend entzündlich gerötet; kein sichtbarer Nekrosenbelag.': ['Rötung', 'Exsudat'],
    'Kleine rundliche Ulzeration mit gelblich-fibrinösem Belag, flach bis mäßig tief; kein sichtbares nekrotisches Gewebe.': ['Ulzeration', 'Fibrinbelag'],
    'Kraterförmige Ulzeration mit überwiegend gelblich-weißem fibrinösem Belag (Slough) und Anteilen rötlichen, feuchten Granulationsgewebes; kein schwarz nekrotisches Gewebe erkennbar.': ['Ulzeration', 'Fibrinbelag', 'Granulation'],
    'Kraterförmiges Ulkus mit gelblichen fibrinösen Belägen, teilweise rötlich-granulierende Areale; mäßig exsudierend.': ['Ulzeration', 'Fibrinbelag', 'Rötung', 'Granulation', 'Exsudat'],
    'Kräftig rot, homogen granulierend, feucht-glänzend ohne sichtbare Nekrosen oder dicke Fibrinbeläge.': ['Rötung', 'Granulation'],
    'Livide bis schwärzliche Areale mit partiell intakten/rupturierten Blasen; oberflächliche Hautnekrosen, kein sichtbares Granulationsgewebe; flächige Beteiligung ohne erkennbare Taschen.': ['Blasenbildung', 'Nekrose'],
    'Mehrere flache bis mäßig vertiefte, teilweise konfluierende Ulzera mit ausgedehntem gelb-grünlichem fibrinösem Belag/Slough; stellenweise rötliche, feinkörnige Granulation sichtbar; feucht glänzend; keine schwarze Nekrose.': ['Ulzeration', 'Fibrinbelag', 'Granulation'],
    'Mehrere flache, rundliche Ulzera mit gelblichen Fibrinbelägen, teils rötliche Granulationsinseln; feucht glänzend.': ['Ulzeration', 'Fibrinbelag', 'Rötung', 'Granulation'],
    'Mehrere oberflächliche Läsionen (Erosionen/Ulzera) mit gelb-beigen Fibrinbelägen und rötlicher Granulation; feucht-glänzend; keine schwarze Nekrose sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Granulation'],
    'Mehrere oberflächliche Ulzerationen mit gelblich-grünlichem fibrinösem Belag, feucht; teils rote Granulationsinseln.': ['Ulzeration', 'Fibrinbelag', 'Granulation', 'Rötung'],
    'Mehrere sakrale Ulzera, teils tiefer liegend; gemischter Wundgrund mit rötlichem Granulationsgewebe und gelblichen Fibrinbelägen; feucht.': ['Ulzeration', 'Granulation', 'Fibrinbelag', 'Rötung'],
    'Mehrere tiefe Ulzera mit gelblich-weißem Fibrinbelag und schwarzer Nekrose, feucht, teils mit Taschenbildung.': ['Ulzeration', 'Fibrinbelag', 'Nekrose', 'Taschenbildung'],
    'Mehrere ulzerierende Läsionen, teils mit schwarzer Nekrose/Eschar, teils gelb-fibrinös belegt; randständig teils rötlich, vereinzelt feuchte Areale mit beginnender Granulation.': ['Ulzeration', 'Nekrose', 'Fibrinbelag', 'Rötung', 'Granulation'],
    'Mehrere zirkuläre bis ovale, flache bis mäßig tiefe Ulzera mit gelblich-beigen Fibrinbelägen/Slough; zentral/peripher rötliche Granulationsinseln; feucht glänzend; keine trockene Schwarznekrose sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Granulation'],
    'Oberflächlich bis mäßig tiefes Ulkus mit gelblich-fibrinösen Belägen und Anteilen rötlicher Granulation.': ['Ulzeration', 'Fibrinbelag', 'Rötung', 'Granulation'],
    'Oberflächliche Ulzeration mit gelb-grünlichem Fibrin-/Slough-Belag, stellenweise rötliche Granulation sichtbar; feucht, unregelmäßige Kontur, glänzende Oberfläche.': ['Ulzeration', 'Fibrinbelag', 'Granulation'],
    'Oberflächliche Ulzerationen mit gelblichen Fibrinbelägen und Anteilen von feuchtem rotem Granulationsgewebe; keine schwarze Nekrose sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Rötung', 'Granulation'],
    'Oberflächliche, feuchte, rötliche Dermis mit erosiven Arealen; multiple intakte und rupturierte seröse Blasen; kein nekrotisches Gewebe sichtbar.': ['Rötung', 'Blasenbildung'],
    'Oberflächliche, teils nässende Erosionen mit gerötetem Wundgrund; keine tiefe Nekrose sichtbar.': ['Rötung', 'Exsudat'],
    'Oberflächlicher, größerer Defekt mit gelblich-fibrinösen Belägen und teils rötlicher Granulation; feucht glänzend, kein schwarzes Nekrosegewebe sichtbar.': ['Fibrinbelag', 'Rötung', 'Granulation'],
    'Oberflächliches Ulkus mit ausgedehnten gelblichen Fibrinbelägen, teils rötlich granulierend; feucht glänzend.': ['Ulzeration', 'Fibrinbelag', 'Rötung', 'Granulation'],
    'Oberflächliches Ulkus mit gelb-grünlichem Fibrin-/Belag, teils nekrotisch; feucht, unregelmäßiger Wundgrund.': ['Ulzeration', 'Fibrinbelag', 'Nekrose'],
    'Oberflächliches Ulkus mit gelblich-fibrinösen Belägen, randständig teils granulierend; kleine zweite Läsion lateral.': ['Ulzeration', 'Fibrinbelag', 'Granulation'],
    'Ovaler Defekt mit zentralem gelblich-beigem Fibrin/Slough, peripher rötliches granulierendes Gewebe; feucht-glänzende Oberfläche; keine sichtbare trockene Nekrose oder freiliegende tiefe Strukturen.': ['Ulzeration', 'Fibrinbelag', 'Granulation'],
    'Ovale, mäßig tiefe Ulzeration mit überwiegend rötlichem, feuchtem Granulationsgewebe; randständig teils adhärente gelblich-fibrinöse Beläge; keine schwarze Nekrose sichtbar.': ['Ulzeration', 'Granulation', 'Fibrinbelag'],
    'Ovale, flache Ulzeration mit überwiegend gelblich-fibrinösem Belag (ca. 70-80%) und dazwischen rötlicher, feucht glänzender Granulation (ca. 20-30%); keine schwarze Nekrose, keine sichtbare Sehnen- oder Knochenexposition.': ['Ulzeration', 'Fibrinbelag', 'Granulation'],
    'Punktförmige, schlitzartige Fistelöffnung(en); Wundgrund nicht einsehbar. Eine Öffnung mit klar-gelblich seröser Flüssigkeit; kein sichtbarer Fibrin- oder Nekrosebelag.': ['Ulzeration', 'Exsudat'],
    'Runde Ulzeration mit zentral gelblich-fibrinösem Belag, mäßig feucht; peripher schmaler erythematöser Saum, kein freiliegender Knochen/Sehne sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Rötung'],
    'Runder, kraterförmiger Defekt mit überwiegend gelblich-fibrinösem Belag; feucht glänzend; keine schwarze Nekrose sichtbar; kaum bis keine erkennbare Granulation.': ['Ulzeration', 'Fibrinbelag'],
    'Rundliche Ulzeration mit überwiegend gelblich-fibrinösem Belag; punktuell rote, feuchte Areale/Granulationsinseln; glänzend-feucht, keine schwarze Nekrose sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Granulation'],
    'Stark nässend; dicke gelb-grünliche Fibrin-/Beläge mit mutmaßlichem Biofilm, teils nekrotische Areale; kaum Granulation sichtbar.': ['Fibrinbelag', 'Biofilm', 'Nekrose', 'Exsudat'],
    'Tief klaffende, längsovale Wunde; Wundgrund überwiegend mit dicken gelb-beigen fibrinösen Belägen/Slough bedeckt, teils graugelb; feucht-glänzend; kaum/kein sichtbares Granulationsgewebe; unregelmäßige Taschen/Kavernen erkennbar.': ['Fibrinbelag', 'Taschenbildung'],
    'Tiefes Ulkus mit gelb- bis grünlichem Fibrin-/Belag, teils avital, Biofilm-verdächtig; Höhle mit möglicher Unterminierung; geringe Inseln von Granulation.': ['Ulzeration', 'Fibrinbelag', 'Biofilm', 'Unterminierung', 'Granulation'],
    'Tiefes, kavernöses Areal mit überwiegend gelb-braunem, dickem fibrinös-purulentem Belag; vereinzelte nekrotische Areale; kaum sichtbares vitales Granulationsgewebe; feucht glänzend.': ['Fibrinbelag', 'Nekrose', 'Taschenbildung'],
    'Tiefes, rundes Ulkus mit zentral gelb-weißem Fibrin/nekrotischen Anteilen; feuchte Beläge, mehere Läsionen sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Nekrose'],
    'Tiefe moderat, kavitäre Ulzeration mit überwiegend gelblich-cremigem fibrinösem Belag/Slough; stellenweise rötliche Granulationsinseln an der Innenwand; feucht mit dickflüssigem Exsudat; keine freiliegenden Knochen oder Sehnen sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Granulation', 'Exsudat'],
    'Tiefe moderat, Wundbett nahezu vollständig (ca. 90-100%) mit gelb-beigem, faserigem Fibrin/Slough bedeckt; kein schwarzer Schorf sichtbar; kaum bis keine Granulation erkennbar; vereinzelte rötliche Areale am Boden; Wunde klar begrenzt, feucht-glänzendem, keine offen erkennbaren freiliegenden tieferen Strukturen.': ['Fibrinbelag', 'Rötung'],
    'Tiefer Defekt mit überwiegend vitalem, feuchtem Granulationsgewebe; randständig gelblich-fibrinöse Beläge.': ['Granulation', 'Fibrinbelag'],
    'Tieferes Ulkus mit dicken gelb-gräulichen Fibrinbelägen, feucht; kaum sichtbares Granulationsgewebe.': ['Ulzeration', 'Fibrinbelag'],
    'Überwiegend gelb-grauer, dicker fibrinöser/slough-Belag mit teils nekrotischem Aspekt; feucht, zäh; kaum bis kein vitales Granulationsgewebe sichtbar; Anzeichen von Tiefe/Unterminierung.': ['Fibrinbelag', 'Nekrose', 'Taschenbildung'],
    'Überwiegend gelb-grünlicher fibrinöser Belag; zentral schwarz-brauner Nekroseanteil (Eschar); feuchte, glänzende Oberfläche; keine sichtbare Granulation oder Epithelinseln.': ['Fibrinbelag', 'Nekrose'],
    'Überwiegend gelb-weißlicher Fibrin-/Slough-Belag mit einzelnen Arealen rötlicher Granulation; feucht-glänzende Oberfläche; keine schwarze Nekrose sichtbar; keine freiliegenden tieferen Strukturen erkennbar.': ['Fibrinbelag', 'Granulation'],
    'Überwiegend gelb-weißlicher Fibrin-/Slough-Belag mit einzelnen grau-schwarzen nekrotischen Arealen; randständig geringe rötliche Gewebeanteile; unregelmäßiger, teilweise kavitiert; feucht glänzend; keine exponierten Knochen/Sehnen sichtbar.': ['Fibrinbelag', 'Nekrose', 'Rötung', 'Taschenbildung'],
    'Überwiegend gelblich-beiger Fibrinbelag/Slough (~70%) mit randständiger rötlicher, feucht-glänzender Granulation; keine schwarze Nekrose sichtbar; vereinzelte punktförmige Blutungen.': ['Fibrinbelag', 'Rötung', 'Granulation'],
    'Überwiegend gelblich-beiger fibrinöser Belag mit Anteilen rötlicher, feucht-glänzender Granulation; keine schwarze Nekrose sichtbar; vereinzelte punktförmige Blutungen.': ['Fibrinbelag', 'Rötung', 'Granulation'],
    'Überwiegend gelblich-weißer Fibrinbelag/Slough mit einzelnen rötlichen Granulationsinseln; feucht-glänzend; oberflächlich bis mitteltief; kein trockener schwarzer Nekroseschorf; keine freiliegenden Sehnen oder Knochen sichtbar.': ['Fibrinbelag', 'Granulation'],
    'Überwiegend gelblich-weißer Fibrinbelag/Biofilm, dazwischen kleine Inseln granulierenden, roten Gewebes; feucht glänzend.': ['Fibrinbelag', 'Biofilm', 'Granulation', 'Rötung'],
    'Überwiegend rötlich granulierendes Gewebe mit ausgedehnten gelblich-cremigen Fibrinbelägen/Slough; vereinzelt dunklere (bräunlich-schwarze) Beläge distal; feucht glänzend; keine freiliegenden Sehnen oder Knochen erkennbar.': ['Fibrinbelag', 'Nekrose', 'Rötung', 'Granulation'],
    'Überwiegend vitales, feuchtes Granulationsgewebe mit geringen fibrinösen Belägen.': ['Granulation', 'Fibrinbelag'],
    'Ulzeration mit gelblich-fibrinösem Belag am Rand, zentral teils vitales rötliches Granulationsgewebe; mäßig tiefe Kavität, keine trockene Nekrose sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Rötung', 'Granulation', 'Taschenbildung'],
    'Unregelmäßig konfiguriertes, eher flaches Ulkus mit überwiegend gelblich-weißlichen fibrinösen Belägen und zähem Exsudat; dazwischen rötliche, feucht-körnige Granulation; keine schwarze Nekrose sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Granulation', 'Exsudat'],
    'Weitgehend rötlich-granulierend mit teils fibrinösen Belägen; feucht glänzend, mehere oberflächliche Läsionen im Cluster.': ['Rötung', 'Granulation', 'Fibrinbelag'],
    'Zentral schwarz-braune Nekrose, umgebend gelblich-fibrinöser Belag mit feuchtem Exsudatfilm; kein vitales Granulationsgewebe erkennbar.': ['Nekrose', 'Fibrinbelag', 'Exsudat'],
    'Zentral schwarz-braune Eschar mit fest anhaftenden Belägen; randständig livid-erythematös und leicht erhaben.': ['Nekrose', 'Rötung'],
    'Zentral trockene schwarz‑braune Nekrose (Eschar) mit gelblich‑bräunlichem Fibrin/Schorf; kein sichtbares Granulations- oder Epithelgewebe.': ['Nekrose', 'Fibrinbelag'],
    'Zwei Läsionen: kaudal ausgedehnte schwarze Nekrose (Eschar), kranial gelb-grünlicher fibrinöser Belag; feuchtes Milieu, kein sichtbares Granulationsgewebe.': ['Nekrose', 'Fibrinbelag'],
    'Zwei oberflächliche Ulzerationen mit gelblichen fibrinösen Belägen, teils rötlich granulierend, feucht; keine ausgedehnte trockene Nekrose sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Rötung', 'Granulation'],
    'Zwei ulzerierende Läsionen mit dickem gelb-weißlichem Fibrinbelag/Detritus und viskösem Exsudat; kein freiliegender Knochen oder Sehne sichtbar.': ['Ulzeration', 'Fibrinbelag', 'Exsudat'],
    'Zwei Ulzera mit gelb-grünlichen Fibrinbelägen und teils schwarzer Nekrose; feuchter Wundgrund mit randständiger Rötung.': ['Ulzeration', 'Fibrinbelag', 'Nekrose', 'Rötung'],
    'Zwei Ulzera: oberes Ulkus mit dickem gelblich-grünlichem Fibrin-/Schmierbelag, feucht glänzend; unteres, größeres Ulkus mit ausgedehnter schwarzer, teils feucht glänzender Nekrose/Eschare. Kein sichtbar vitales Granulations- oder Epithelgewebe; Beläge überwiegend adhärent.': ['Ulzeration', 'Fibrinbelag', 'Nekrose'],

    # ---- Neue Mappings aus wundgrund_mapping.md ----
    "Tiefere Wunde mit dicken gelblichen fibrinösen Belägen/Detritus, kaum sichtbare Granulation; möglicherweise Wundtaschen.": ["Fibrinbelag", "Granulation", "Taschenbildung"],
    "Oberflächliche, teils nässende Erosionen mit gerötetem Wundgrund; keine tiefe Nekrose sichtbar.": ["Rötung"],
    "Kräftig rot, homogen granulierend, feucht-glänzend ohne sichtbare Nekrosen oder dicke Fibrinbeläge.": ["Rötung", "Granulation"],
    "Zwei ulzerierende Läsionen mit dickem gelb-weißlichem Fibrinbelag/Detritus und viskösem Exsudat; kein freiliegender Knochen oder Sehne sichtbar.": ["Ulzeration", "Fibrinbelag", "Exsudat"],
    "Ausgedehnte gelblich-fibrinöse Beläge mit schwarz-braunen Nekrosen, dazwischen rötliche granulierende Areale; feucht-glänzend.": ["Fibrinbelag", "Nekrose", "Rötung", "Granulation"],
    "Oberflächliche, feuchte, rötliche Dermis mit erosiven Arealen; multiple intakte und rupturierte seröse Blasen; kein nekrotisches Gewebe sichtbar.": ["Rötung", "Blasenbildung"],
    "Feucht glänzender, teils gelblich fibrinös belegter Wundgrund mit fragiler Granulation, oberflächlich, keine erkennbaren Taschen.": ["Fibrinbelag", "Granulation"],
    "Livide bis schwärzliche Areale mit partiell intakten/rupturierten Blasen; oberflächliche Hautnekrosen, kein sichtbares Granulationsgewebe; flächige Beteiligung ohne erkennbare Taschen.": ["Blasenbildung", "Nekrose"],
    "Großflächige trockene, schwarze Eschar lateral am Rückfuß/Ferse; kleinere nekrotische Läsion am lateralen Zehenbereich. Umgebung teils stark gerötet, glänzend, keine sichtbare Granulation.": ["Nekrose", "Rötung"],
    "Gemischtes Wundbett mit schwarzen nekrotischen Arealen und gelb-grauem Fibrinbelag; zentral rötliches, feuchtes Granulationsgewebe; tiefe Ulzeration mit möglicher Unterminierung.": ["Nekrose", "Fibrinbelag", "Rötung", "Granulation", "Ulzeration", "Unterminierung"],
    "Mehrere ulzerierende Läsionen, teils mit schwarzer Nekrose/Eschar, teils gelb-fibrinös belegt; randständig teils rötlich, vereinzelt feuchte Areale mit beginnender Granulation.": ["Ulzeration", "Nekrose", "Fibrinbelag", "Rötung", "Granulation"],
    "Tiefer Defekt mit überwiegend vitalem, feuchtem Granulationsgewebe; randständig gelblich-fibrinöse Beläge.": ["Granulation", "Fibrinbelag"],
    "Oberflächliche Ulzerationen mit gelblichen Fibrinbelägen und Anteilen von feuchtem rotem Granulationsgewebe; keine schwarze Nekrose sichtbar.": ["Ulzeration", "Fibrinbelag", "Rötung", "Granulation"],
    "Gemischt: überwiegend rote Granulation mit teils gelblich-fibrinösen Belägen; feuchter Wundgrund.": ["Rötung", "Granulation", "Fibrinbelag"],
    "Mehrere tiefe Ulzera mit gelblich-weißem Fibrinbelag und schwarzer Nekrose, feucht, teils mit Taschenbildung.": ["Ulzeration", "Fibrinbelag", "Nekrose", "Taschenbildung"],
    "Weitgehend rötlich-granulierend mit teils fibrinösen Belägen; feucht glänzend, mehrere oberflächliche Läsionen im Cluster.": ["Rötung", "Granulation", "Fibrinbelag"],
    "Mehrere flache, rundliche Ulzera mit gelblichen Fibrinbelägen, teils rötliche Granulationsinseln; feucht glänzend.": ["Ulzeration", "Fibrinbelag", "Rötung", "Granulation"],
    "Zwei oberflächliche Ulzerationen mit gelblichen fibrinösen Belägen, teils rötlich granulierend, feucht; keine ausgedehnte trockene Nekrose sichtbar.": ["Ulzeration", "Fibrinbelag", "Rötung", "Granulation"],
    "Oberflächlich bis mäßig tiefes Ulkus mit gelblich-fibrinösen Belägen und Anteilen rötlicher Granulation.": ["Ulzeration", "Fibrinbelag", "Rötung", "Granulation"],
    "Zwei Ulzera mit gelb-grünlichen Fibrinbelägen und teils schwarzer Nekrose; feuchter Wundgrund mit randständiger Rötung.": ["Ulzeration", "Fibrinbelag", "Nekrose", "Rötung"],
    "Ausgedehnte schwarz-braune Nekrose/Eschar mit feucht-glänzender Oberfläche, teils fibrinös belegt; keine Granulation sichtbar.": ["Nekrose", "Fibrinbelag"],
    "Großflächige, trockene schwarze Eschar (nekrotisches Gewebe) am Fersenpolster, keine sichtbare Granulation oder Sickerblutung.": ["Nekrose"],
    "Kleines rundes Ulkus mit gelblich-fibrinösem Belag; kein freiliegendes tieferes Gewebe sichtbar.": ["Ulzeration", "Fibrinbelag"],
    "Überwiegend gelblich-weißlicher fibrinöser Belag mit Anteilen rötlicher Granulation; kein freiliegender Knochen sichtbar.": ["Fibrinbelag", "Rötung", "Granulation"],
    "Gelblich-weißer, zäher fibrinöser Belag mit wenigen punktförmigen Blutungen; feucht, vereinzelte rötliche Areale.": ["Fibrinbelag", "Rötung"],
    "Tiefes, rundes Ulkus mit zentral gelb-weißem Fibrin/nekrotischen Anteilen; feuchte Beläge, mehrere Läsionen sichtbar.": ["Ulzeration", "Fibrinbelag", "Nekrose"],
    "Schwarze Nekrosenanteile mit dicken gelb-grünlichen fibrinösen Belägen, feucht; peripher teils gerötetes/angegriffenes Gewebe.": ["Nekrose", "Fibrinbelag", "Rötung"],
    "Gemischter Wundgrund mit gelblichen fibrinösen Belägen/Slough und rötlichem Granulationsgewebe; feucht, mäßige Tiefe; kein freiliegender Knochen sichtbar.": ["Fibrinbelag", "Rötung", "Granulation"],
    "Zentrale schwarz-gelbe Eschar mit fest anhaftenden Belägen; randständig livid-erythematös und leicht erhaben.": ["Nekrose"],
    "Flaches, irreguläres Ulkus mit gelblich-fibrinösen Belägen und Anteilen von Granulationsgewebe; feucht.": ["Ulzeration", "Fibrinbelag", "Granulation"],
    "Gelb-beiger, feuchter fibrinöser Belag/flächiger Slough, kaum Granulation sichtbar.": ["Fibrinbelag"],
    "Feuchtes, teils granulierendes Wundbett mit ausgeprägten gelb-weißlichen Fibrinbelägen; keine trockene Nekrose erkennbar.": ["Granulation", "Fibrinbelag"],
    "Runde Ulzeration mit zentral gelblich-fibrinösem Belag, mäßig feucht; peripher schmaler erythematöser Saum, kein freiliegender Knochen/Sehne sichtbar.": ["Ulzeration", "Fibrinbelag", "Rötung"],
    "Feuchtes, gut durchblutetes granulierendes Wundbett mit kleinen, fest anhaftenden fibrinösen Inseln/Belägen; kein nekrotisches Gewebe sichtbar.": ["Granulation", "Fibrinbelag"],
    "Oberflächliches Ulkus mit gelb-grünlichem Fibrin-/Belag, teils nekrotisch; feucht, unregelmäßiger Wundgrund.": ["Ulzeration", "Fibrinbelag", "Nekrose"],
    "Fibrinös-gelblicher Belag mit Inseln rötlicher Granulation; feucht, keine trockene Nekrose sichtbar.": ["Fibrinbelag", "Rötung", "Granulation"],
    "Gelb‑bräunlicher Fibrinbelag mit zentralen schwarz‑nekrotischen Arealen; kaum/keine sichtbare Granulation.": ["Fibrinbelag", "Nekrose"],
    "Oberflächliches Ulkus mit ausgedehnten gelblichen Fibrinbelägen, teils rötlich granulierend; feucht glänzend.": ["Ulzeration", "Fibrinbelag", "Rötung", "Granulation"],
    "Flache, ovale Ulzeration mit zentral gelblichen Fibrinbelägen; randständig rötliche, feuchte Granulation.": ["Ulzeration", "Fibrinbelag", "Granulation", "Rötung"],
    "Kleiner runder Ulkus (~1.5–2 cm) mit gelblich-weißen fibrinösen Belägen, punktuell rötlich/blasende Areale; oberflächlich und feucht.": ["Ulzeration", "Fibrinbelag", "Rötung", "Blasenbildung"],
    "Überwiegend gelblich-weißer Fibrinbelag/Biofilm, dazwischen kleine Inseln granulierenden, roten Gewebes; feucht glänzend.": ["Fibrinbelag", "Biofilm", "Granulation", "Rötung"],
    "Ulzeration mit gelblich-fibrinösem Belag am Rand, zentral teils vitales rötliches Granulationsgewebe; mäßig tiefe Kavität, keine trockene Nekrose sichtbar.": ["Ulzeration", "Fibrinbelag", "Rötung", "Granulation"],
    "Stark nässend; dicke gelb-grünliche Fibrin-/Beläge mit mutmaßlichem Biofilm, teils nekrotische Areale; kaum Granulation sichtbar.": ["Fibrinbelag", "Biofilm", "Nekrose"],
    "Großflächiger gelb‑grünlicher Fibrinbelag/Slough mit einzelnen nekrotischen Arealen distal; feucht, kaum sichtbare Granulation.": ["Fibrinbelag", "Nekrose"],
    "Oberflächlicher, größerer Defekt mit gelblich-fibrinösen Belägen und teils rötlicher Granulation; feucht glänzend, kein schwarzes Nekrosegewebe sichtbar.": ["Fibrinbelag", "Rötung", "Granulation"],
    "Kleines, ovales Ulkus mit gelblich-fibrinösem Belag; feucht, keine freiliegenden Strukturen sichtbar.": ["Ulzeration", "Fibrinbelag"],
    "Zentral schwarz-braune Nekrose, umgebend gelblich-fibrinöser Belag mit feuchtem Exsudatfilm; kein vitales Granulationsgewebe erkennbar.": ["Nekrose", "Fibrinbelag"],
    "Gelblich-fibrinös belegter, feucht-glänzender Wundgrund mit teils rötlichen Arealen; kein trockener Nekroseanteil sichtbar.": ["Fibrinbelag", "Rötung"],
    "Mehrere oberflächliche Ulzerationen mit gelblich-grünlichem fibrinösem Belag, feucht; teils rote Granulationsinseln.": ["Ulzeration", "Fibrinbelag", "Granulation", "Rötung"],
    "Granulierender Wundgrund mit ausgeprägten gelblichen fibrinösen Belägen/Slough, teils adhärent; vereinzelt dunklere nekrotische Areale distal.": ["Granulation", "Fibrinbelag", "Nekrose"],
    "Kleine rundliche Ulzeration mit gelblich-fibrinösem Belag, flach bis mäßig tief; kein sichtbares nekrotisches Gewebe.": ["Ulzeration", "Fibrinbelag"],
    "Oberflächliches Ulkus mit gelblich-fibrinösen Belägen, randständig teils granulierend; kleine zweite Läsion lateral.": ["Ulzeration", "Fibrinbelag", "Granulation"],
    "Kraterförmiges Ulkus mit gelblichen fibrinösen Belägen, teilweise rötlich-granulierende Areale; mäßig exsudierend.": ["Ulzeration", "Fibrinbelag", "Rötung", "Granulation"],
    "Zwei Läsionen: kaudal ausgedehnte schwarze Nekrose (Eschar), kranial gelb-grünlicher fibrinöser Belag; feuchtes Milieu, kein sichtbares Granulationsgewebe.": ["Nekrose", "Fibrinbelag"],
    "Tiefes Ulkus mit gelb- bis grünlichem Fibrin-/Belag, teils avital, Biofilm-verdächtig; Höhle mit möglicher Unterminierung; geringe Inseln von Granulation.": ["Ulzeration", "Fibrinbelag", "Biofilm", "Unterminierung", "Granulation"],
    "Ovales Ulkus mit dicken gelb-weißlichen Fibrinbelägen, zentral teils grau-schwarze nekrotische Areale; kaum sichtbare Granulation.": ["Ulzeration", "Fibrinbelag", "Nekrose"],
    "Tieferes Ulkus mit dicken gelb-gräulichen Fibrinbelägen, feucht; kaum sichtbares Granulationsgewebe.": ["Ulzeration", "Fibrinbelag"],
    "Kleine punktförmige Öffnungen/Pusteln mit serösem bis seropurulentem Exsudat, umgebend entzündlich gerötet; kein sichtbarer Nekrosenbelag.": ["Rötung", "Exsudat"],
    "Überwiegend vitales, feuchtes Granulationsgewebe mit geringen fibrinösen Belägen.": ["Granulation", "Fibrinbelag"],
    "Mehrere sakrale Ulzera, teils tiefer liegend; gemischter Wundgrund mit rötlichem Granulationsgewebe und gelblichen Fibrinbelägen; feucht.": ["Ulzeration", "Granulation", "Fibrinbelag", "Rötung","Feucht"],
    "starke Granulation, überschießendes Gewebe, infektfrei": ["Granulation", "Hypergranulation"],
    "Hämangiome sind Neoplasien ( Neubildungen) , umschriebenes Hämangiom, klare Abgrenzung. segmentale Fehlbildung.\nBehandlung unbedingt notwendig.": ["Hämangiom"],
    "Exsudation": ["Exsudat"],

    # ---- Few-Shot & 2-Stage LLM Wundgrund Mappings ----
    "Tiefer Defekt mit dicken gelblichen Fibrin-/Schleimbelägen, teils nekrotisch; kaum Granulation sichtbar.": ["Fibrinbelag", "Nekrose"],
    "Vitales, homogen granulierendes Gewebe, feucht glänzend, keine sichtbaren Beläge oder Nekrosen.": ["Granulation"],
    "Großflächige schwarze/braune Nekrosen und gelblich-fibrinöse Beläge, teils feucht; randständig kleine Areale mit frischer Blutung/Granulation.": ["Fibrinbelag", "Granulation", "Nekrose"],
    "Teilweise freiliegende, feucht-rosige Dermis mit oberflächlichen Erosionen; mehrere intakte und rupturierte seröse Blasen, vereinzelte dünne Fibrinauflagen.": ["Blasenbildung", "Fibrinbelag"],
    "Flächig oberflächlich erosiv, feucht glänzend mit teils fibrinösen Belägen und rötlich-granulierenden Arealen.": ["Fibrinbelag", "Granulation"],
    "Kein freiliegender Wundgrund sichtbar; intakte bzw. teils abgehobene Epidermis mit Hämatom und Blasen": ["Blasenbildung", "Hämatom"],
    "Großflächig trockene schwarze Nekrosen (Eschar) an Ferse und lateraler Fußseite; kleinere Areale mit gelblich-fibrinösem Belag proximal; keine erkennbare Granulation.": ["Fibrinbelag", "Nekrose"],
    "Ausgedehnte schwarz-braune Nekrosen mit gelblich-fibrinösen Belägen; zentral rötlich-granulierende Anteile; unregelmäßiger, teils tiefer Defekt.": ["Fibrinbelag", "Granulation", "Nekrose"],
    "Schwarz-braune Nekrosen und fest anhaftende Fibrinbeläge; teils blutiges, freiliegendes Gewebe am Vorfuß; mehrere oberflächliche bis mäßig tiefe Ulzera.": ["Fibrinbelag", "Nekrose"],
    "Granulierendes Gewebe mit gelblich-fibrinösen Belägen; schräger, mäßig tiefer Defekt mit möglicher Randunterminierung; feucht glänzend.": ["Fibrinbelag", "Granulation", "Taschenbildung"],
    "Gemischt: gelblich-fibrinöse Beläge mit Anteilen von feuchter Granulation; unregelmäßige, flach bis mäßig tiefe Läsion.": ["Fibrinbelag", "Granulation"],
    "Flacher Defekt mit überwiegender roter Granulation und teils gelblich-fibrinösen Belägen; keine trockene Nekrose sichtbar.": ["Fibrinbelag", "Granulation"],
    "Mehrere tiefe Ulzerationen mit gelblich-fibrinösen Belägen und schwarzer Nekrose, teilweise rötlich-granulierende Areale, feucht.": ["Fibrinbelag", "Granulation", "Nekrose"],
    "vitalrotes, glänzend-feuchtes Granulationsgewebe, teils bereits beginnende Epithelisierung, keine Nekrosen sichtbar": ["Granulation", "Wundrandepithelisierung"],
    "Mehrere flache Ulzera mit gelblich-fibrinösen Belägen, teils granuliert; einzelne Blutkrusten, kein freiliegender Knochen/Sehne sichtbar.": ["Fibrinbelag", "Granulation"],
    "gelblich-brauner Fibrinbelag mit teils rötlichen Anteilen; keine freiliegenden Strukturen sichtbar": ["Fibrinbelag"],
    "Gemischter Wundgrund mit gelb-grünlichen Fibrinbelägen und teils schwarzer trockener Nekrose; teilweise gerötete, leicht feuchte Umgebung; geringe Blutungsspuren": ["Fibrinbelag", "Nekrose"],
    "Großflächige schwarz-braune, teils feucht glänzende Nekrose/Schorf ohne sichtbares vitales Gewebe; Übergangszonen mit grauen Belägen.": ["Fibrinbelag", "Nekrose"],
    "Großflächige, schwarz-braune, trockene Nekrose/Eschar; keine sichtbare Granulation, minimaler erythematöser Saum": ["Nekrose"],
    "Punktförmige Läsion mit gelb-grünlichem Belag/Eiterpfropf, Tiefe unklar.": ["Fibrinbelag"],
    "Zentral gelblicher fibrinöser Belag, randständig teils rötliche Granulation; kein freiliegender Knochen sichtbar.": ["Fibrinbelag", "Granulation"],
    "Großflächiger gelblich-fibrinöser Belag, teils serös‑blutig unterlaufen; oberflächlicher bis teildermaler Substanzverlust.": ["Fibrinbelag"],
    "gelblich-fibrinös belegter, teils nekrotischer Wundgrund mit Ulkuskrater; zweite Läsion mit trockener Nekrose/Schorf": ["Fibrinbelag", "Nekrose"],
    "Ausgedehnter schwarz-brauner Nekroseanteil mit gelblich-grünem Fibrin/Slough, feucht glänzend; möglicher Biofilm": ["Biofilm", "Fibrinbelag", "Nekrose"],
    "Gelb-weißliche fibrinöse Beläge mit rötlich granulierenden Arealen; feuchter Wundgrund.": ["Fibrinbelag", "Granulation"],
    "Zentrale schwarz-braune Eschar mit gelblich-fibrinösen Arealen; verhärteter, livid-erythematöser Rand.": ["Fibrinbelag", "Nekrose", "Rötung"],
    "Irregulärer Ulkus mit gelblichen fibrinösen Belägen und Anteilen rötlicher Granulation; feucht glänzend.": ["Fibrinbelag", "Granulation"],
    "Gelblicher, zäher Fibrinbelag; kaum Granulation; teils tieferliegendes Gewebe/Faszie sichtbar.": ["Fibrinbelag"],
    "Großflächig, feucht; überwiegend rote Granulation mit gelblichen fibrinösen Belägen/Slough.": ["Fibrinbelag", "Granulation"],
    "Zentral gelblich-fibrinöser Belag, flach; geringe/keine sichtbare Granulation; kein nekrotisches Gewebe erkennbar.": ["Fibrinbelag"],
    "Überwiegend rot-granulierend mit wenigen gelblich-fibrinösen Inseln; feucht; flach.": ["Fibrinbelag", "Granulation"],
    "ausgedehnter gelblich-fibrinöser Belag/Biofilm mit einzelnen rötlich-granulierenden Anteilen; feucht": ["Biofilm", "Fibrinbelag", "Granulation"],
    "oberflächliche Ulzeration mit gelblich-weißen Fibrinbelägen und vereinzelten rötlich-granulierenden Arealen; keine trockene Nekrose sichtbar": ["Fibrinbelag", "Granulation"],
    "Gelb-bräunliche Fibrinauflagerungen mit zentralen schwarz-braunen Nekroseanteilen; kein Granulationsgewebe sichtbar.": ["Fibrinbelag", "Nekrose"],
    "Ovales Ulkus mit gelblich-fibrinösem Belag, feucht-glänzend; punktuell gerötete Granulation sichtbar.": ["Fibrinbelag", "Granulation"],
    "Ovales, oberflächliches Ulkus mit gelblich-fibrinösem Belag zentral, peripher rötlich granulierend.": ["Fibrinbelag", "Granulation"],
    "Runde, oberflächliche Läsion mit gelblich-fibrinösem Belag und punktuellen Granulationen; feucht glänzend.": ["Fibrinbelag", "Granulation"],
    "Zentral gelblich-weisslicher Fibrinbelag mit zwei rötlichen Granulationsinseln; oberflächlich, feucht.": ["Fibrinbelag", "Granulation"],
    "Ovales Ulkus mit randständigem gelblich-fibrinösem Belag und zentralen Granulationsarealen; keine freiliegenden Strukturen sichtbar.": ["Fibrinbelag", "Granulation"],
    "Ausgedehnte gelb-grünliche Fibrin-/Beläge mit Biofilm, teils weich-nekrotische Areale; feucht, keine freiliegenden Strukturen erkennbar.": ["Biofilm", "Fibrinbelag", "Nekrose"],
    "Ausgedehnter gelb-grünlicher Fibrin-/Detritusbelag mit einzelnen nekrotischen Arealen, kaum Granulation sichtbar; oberflächlich bis flach, unregelmäßige Ränder.": ["Fibrinbelag", "Nekrose"],
    "Weitläufige, flache Ulzeration mit gelblich-fibrinösem Belag, feucht; vereinzelte punktförmige Blutungen; keine freiliegenden Strukturen erkennbar.": ["Fibrinbelag"],
    "Kleiner ovaler Defekt mit gelblich-fibrinösem Belag, kaum sichtbare Granulation, oberflächlich.": ["Fibrinbelag"],
    "Gelb-grünlicher Fibrinbelag mit zentraler schwarz-brauner Nekrose; feucht erscheinend.": ["Fibrinbelag", "Nekrose"],
    "Großflächiger gelblich-bräunlicher fibrinöser Belag mit feuchtem Wundbett; teils rötliche Granulation sichtbar; oberflächlich.": ["Fibrinbelag", "Granulation"],
    "Gelblich-grünlicher Fibrin-/Belag mit teils rötlich punktförmig granulierenden Arealen; oberflächliche, irreguläre Ulzera.": ["Fibrinbelag", "Granulation"],
    "Gemischter Wundgrund mit gelb-weißen Fibrinbelägen und dazwischen vitalem Granulationsgewebe; feucht, oval.": ["Fibrinbelag", "Granulation"],
    "Kleines rundes Ulkus mit gelblich-fibrinösen Belägen, eher trocken; kein deutlich granulierendes Gewebe sichtbar.": ["Fibrinbelag"],
    "Oberflächliches Ulkus mit gelblich-fibrinösen Belägen; randständig teils epithelisierend; zweite kleine oberflächliche Läsion lateral.": ["Fibrinbelag", "Wundrandepithelisierung"],
    "Gelbliche fibrinöse Beläge, teils granulierend; flach-kraterförmiger Defekt.": ["Fibrinbelag", "Granulation"],
    "Ausgedehnte schwarze trockene Nekrose am unteren Ulkus, oberes Ulkus mit gelblichen Fibrinbelägen; kein Granulationsgewebe sichtbar.": ["Fibrinbelag", "Nekrose"],
    "Tiefer Ulkus mit gelblich-fibrinösen Belägen, teils nekrotisch, wenig Granulation; Höhle mit möglicher Randunterminierung.": ["Fibrinbelag", "Granulation", "Nekrose", "Taschenbildung"],
    "Gelb-weißlicher fibrinöser Belag mit zentral dunkler nekrotischer Komponente; bislang kaum Granulation sichtbar.": ["Fibrinbelag", "Nekrose"],
    "Gelb-grauer fibrinöser Belag mit feuchtem Slough; Tiefe/Unterminierungen nicht sicher beurteilbar.": ["Fibrinbelag", "Taschenbildung"],
    "Kleine, serös gefüllte Blase mit möglicher punktueller Erosion; kein nekrotisches Gewebe sichtbar.": ["Blasenbildung"],
    "Rötlich-feuchtes, gut durchblutetes Granulationsgewebe, punktuell dünner Fibrinbelag; keine Nekrosen sichtbar.": ["Fibrinbelag", "Granulation"],
    "Mischbild aus vitalem Granulationsgewebe mit gelblich-fibrinösen Belägen; zwei tiefer reichende Ulzera, kein freiliegender Knochen sichtbar.": ["Fibrinbelag", "Granulation"],
    "Mehrere konfluierende, oberflächlich erodierte Areale mit feucht-glänzend rotem Gewebe; punktuell serös-sanguinöse Anteile; kein nekrotisches Gewebe erkennbar; teils weißliche, schuppige Auflagerungen an und um die Erosionen.": [],
    "Großflächig flaches Areal mit kräftig rotem, feucht-glänzendem, homogenem Granulationsgewebe; keine sichtbaren Nekrosen oder gelblichen Fibrinbeläge; randständige beginnende Epithelisierung.": ["Granulation", "Wundrandepithelisierung"],
    "Zwei tiefe Ulzerationen mit dickem gelblich-weißlichem fibrinösem/purulentem Belag; randständig teils rötliche Granulation; feucht, kein schwarzes Nekrosengewebe sichtbar.": ["Fibrinbelag", "Granulation", "Infektion"],
    "Überwiegend gelblich-beiger, feucht-glänzender Fibrin-/Slough-Belag; ausgedehnte dunkelbraun-schwarze Nekrose-/Escharareale; vereinzelte rötliche Granulationsinseln, vor allem randständig; heterogene Tiefenwirkung": ["Fibrinbelag", "Granulation", "Nekrose"],
    "Mehrere oberflächliche Erosionen mit feuchtem, rosig-rotem, glänzendem Wundgrund; teils intakte seröse Blasen, teils rupturierte Blasen mit freiliegender Dermis; keine sichtbaren Nekrosen oder dicker Fibrinbelag.": ["Blasenbildung"],
    "Flacher, ausgedehnter Defekt mit rötlich granulierendem Gewebe und ausgedehnten gelblich-fibrinösen Belägen; stark feucht/glänzend; keine schwarze Nekrose sichtbar.": ["Fibrinbelag", "Granulation"],
    "Ausgedehnte livid‑violette Hautverfärbung mit deutlicher Schwellung; multiple intakte und kollabierte Blasen (teils serös/serosanguinös gefüllt); oberflächliche Erosionen/Krusten in rechteckigen Arealen; keine sichtbare Granulation, kein freiliegendes tiefes Gewebe erkennbar.": ["Blasenbildung"],
    "Großflächige schwarz-braune, trockene, fest haftende Nekrose (Eschar) an der Ferse/lateralem Rückfuß; weitere kleinere nekrotische Läsion am lateralen Vorfuß nahe dem 5. Strahl; kein sichtbares Granulations- oder Epithelgewebe; stellenweise gelblich-fibrinöse Beläge proximal am Knöchel.": ["Fibrinbelag", "Nekrose"],
    "Gemischter Wundgrund: großflächige schwarz-braune Nekrosen/Eschar und gelb-grauer Fibrinbelag; zentral tieferer Defekt mit rötlichem, feuchtem Granulationsgewebe; unregelmäßig, teilweise kavitiert; feucht glänzend; keine exponierten Knochen/Sehnen sichtbar.": ["Fibrinbelag", "Granulation", "Nekrose"],
    "Mehrere Ulzera: 1) rundliches Ulkus am Fußrand mit zentraler schwarz‑brauner, trockener Nekrose/Eschar; 2) irreguläres Ulkus plantar am Vorfuß/Zehenbasis mit rötlicher Granulation, gelblich-fibrinösen Belägen und teils blutigen Auflagerungen; insgesamt feucht glänzend, keine sichtbaren Sehnen oder Knochen.": ["Fibrinbelag", "Granulation", "Nekrose"],
    "Überwiegend rötliches, feuchtes Granulationsgewebe mit anteilig gelblich-fibrinösen Belägen; unregelmäßige Ulkusränder; teils kavernös wirkend mit Unterminierung; keine schwarze Nekrose sichtbar.": ["Fibrinbelag", "Granulation", "Taschenbildung"],
    "Gemischter Wundgrund mit rötlicher, feucht glänzender Granulation und ausgedehnten gelblich-fibrinösen Belägen; flach und unregelmäßig, teils zusammenfließende Ulzerationen; keine schwarze Nekrose sichtbar.": ["Fibrinbelag", "Granulation"],
    "Großflächige Ulzeration mit überwiegend vitalem, feucht-glänzendem, hell- bis dunkelrotem Granulationsgewebe; eingestreut gelblich-weißliche fibrinöse Beläge (vor allem zentral und distal); keine schwarze Nekrose sichtbar; unregelmäßige Kontur.": ["Fibrinbelag", "Granulation"],
    "Drei rund-ovale, teils tief reichende Defekte mit zentral schwarz-brauner Nekrose (Eschar) und gelblich-weißen fibrinösen Belägen; feucht-glänzende Oberfläche; am Rand abschnittsweise rötliches Granulationsgewebe erkennbar.": ["Fibrinbelag", "Granulation", "Nekrose"],
    "Überwiegend granulierendes, rötlich bis dunkelrotes, feuchtes Gewebe; mehrere flache, teils konfluierende Ulzera; stellenweise dünner gelblicher Fibrinbelag an den Rändern; keine schwarze Nekrose sichtbar.": ["Fibrinbelag", "Granulation"],
    "Multiple rund-ovale, teils konfluierende Ulzera mit gelblich-beigem fibrinösem Belag; Abschnitte mit rötlicher Granulation; vereinzelt hämorrhagische Krusten/Schorfinseln; überwiegend oberflächlich bis partiell dermal, feucht-glänzend ohne sichtbare tiefe Strukturen.": ["Fibrinbelag", "Granulation"],
    "Zwei benachbarte Ulzera: proximal überwiegend gelb-beiger fibrinöser Belag; distal rötlich-feuchtes, teils granuliertes Gewebe. Keine schwarze Nekrose sichtbar. Oberflächlich bis mäßig tief.": ["Fibrinbelag", "Granulation"],
    "Ovales Ulkus, zentral überwiegend gelblich-bräunlicher Fibrinbelag/Slough (~60–70%), peripher rötliche feucht wirkende Granulation (~30–40%); keine freiliegenden Sehnen oder Knochen erkennbar; moderat tief, klar begrenzte Defektzone.": ["Fibrinbelag", "Granulation"],
    "Zwei getrennte Ulzera. Proximal: ovaler Defekt mit überwiegend gelb-grauem Fibrin/Slough (ca. 60-70%), restlich rötlich-feuchtes Gewebe. Distal: gemischter Wundgrund mit randständiger rötlicher Granulation und zentral schwarz-brauner trockener Nekrose/Schorf; teils serös-blutige Beläge. Tiefe bis ins subkutane Gewebe, keine freiliegenden Sehnen oder Knochen sichtbar.": ["Fibrinbelag", "Granulation", "Nekrose"],
    "Großflächige schwarz-braune, teils glänzend-feuchte Eschar/Nekrose, fest haftend; randständig gelblich-graue Beläge; kein vitales Granulations- oder Epithelgewebe sichtbar.": ["Fibrinbelag", "Nekrose"],
    "Wundbett vollständig von trockener, schwarz-brauner, fest anhaftender Ledernekrose (Eschar) bedeckt; teils grauweißliche Anteile; keine sichtbare Granulation oder Epithelisierung.": ["Nekrose"],
    "Kleine runde Öffnung mit gelb-grünlichem purulentem/fibrinösem Belag (Eiterpfropf); kein sichtbares Granulations- oder Epithelgewebe.": ["Fibrinbelag", "Infektion"],
    "Überwiegend gelblich-beiger Fibrinbelag/Slough (~70%) mit randständiger rötlicher, feuchter Granulation (~30%); kein schwarzes Nekrosegewebe sichtbar; Wundbett feucht-glänzend, mäßige Tiefe; keine freiliegenden Strukturen (Knochen/Sehne) erkennbar.": ["Fibrinbelag", "Granulation"],
    "Überwiegend gelblich-beiger, dicker Fibrin-/Belag mit teils grünlicher Tönung, feucht-glänzend; randständig vereinzelte rötliche granulierende Areale und punktförmige Blutungen; keine schwarze Nekrose sichtbar.": ["Fibrinbelag", "Granulation"],
    "Großes rundes Ulkus mit überwiegend gelblich-weißem Fibrin-/Schleimhautbelag, zentral teils rötliche Granulationsinseln; randständig trockene nekrotische Krusten; feucht-glänzend, kein freiliegender Knochen oder Sehne sichtbar.": ["Fibrinbelag", "Granulation", "Nekrose"],
    "Tiefe, kraterförmige Ulzeration mit überwiegend gelblich-weißem fibrinösem Belag (Slough) und Anteilen rötlichen, feuchten Granulationsgewebes; kein schwarz nekrotisches Gewebe erkennbar.": ["Fibrinbelag", "Granulation"],
    "Wundbett nahezu vollständig (ca. 90-100%) mit gelb-beigem, feucht-glänzendem, faserigem Fibrin/Slough bedeckt; kein schwarzer Schorf sichtbar; kaum bis keine Granulation erkennbar; vereinzelte rötliche Areale am Boden; Wunde klar begrenzt, Tiefe moderat, keine offen erkennbaren freiliegenden tieferen Strukturen.": ["Fibrinbelag"],
    "Großflächiger, oberflächlicher bis mäßig tiefer Ulkus mit überwiegend vitaler, feucht glänzender, hell- bis dunkelroter Granulation; multiple gelblich‑weiße Fibrinbeläge/Slough-Inseln; unregelmäßige Oberfläche; keine trockene Nekrose sichtbar.": ["Fibrinbelag", "Granulation"],
    "Zentral überwiegend gelblich-weißlicher fibrinöser Belag (Slough), feucht; randständig schmaler rötlicher Saum mit beginnender Granulation; keine schwarze Nekrose sichtbar.": ["Fibrinbelag", "Granulation"],
    "Überwiegend feucht-rote Granulation, flach; zwei zentral gelegene rundliche weißlich-gelbliche Fibrininseln/Beläge; keine schwarze Nekrose; beginnende Epithelisierung vom Rand.": ["Fibrinbelag", "Granulation", "Wundrandepithelisierung"],
    "Oberflächlicher, irregulär geformter Wundgrund mit überwiegend gelblich-grünlichem fibrinösem Belag/Slough; dazwischen rötliche, feucht-glänzende Granulation; kein trockener Nekroseanteil; flach ohne sichtbare Taschen.": ["Fibrinbelag", "Granulation"],
    "Ovale, flache Ulzeration mit überwiegend gelblich-fibrinösem Belag (ca. 70–80%) und dazwischen rötlicher, feucht glänzender Granulation (ca. 20–30%); keine schwarze Nekrose, keine sichtbare Sehnen- oder Knochenexposition.": ["Fibrinbelag", "Granulation"],
    "Überwiegend dicke gelb-grüne, schmierig-fibrinöse Beläge mit purulentem, viskösem Exsudat; dazwischen rötliche Granulationsinseln; einzelne bräunlich-dunklere Areale; Wundbett feucht und unregelmäßig, keine freiliegenden Sehnen oder Knochen sichtbar.": ["Exsudat", "Fibrinbelag", "Granulation", "Infektion"],
    "Oberflächliches, ovales Ulkus mit überwiegend gelblich-weißlichem, feuchtem Fibrinbelag; stellenweise rötliche Granulation sichtbar; keine schwarze Nekrose; unregelmäßige Kontur, glänzende Oberfläche.": ["Fibrinbelag", "Granulation"],
    "Hauptläsion: flaches, ovales Ulkus mit gelblich-beigem fibrinösem Belag, randständig teils rötlich, feucht glänzend; keine schwarze Nekrose, keine sichtbaren tieferen Strukturen. Zweite kleinere, oberflächliche Läsion lateral mit rötlichem, feuchtem Wundbett.": ["Fibrinbelag", "Rötung"],
    "Überwiegend gelb-weißlicher fibrinöser Belag (Slough), stellenweise rötliche Granulation sichtbar; feucht, unregelmäßig-kraterförmig; keine trockene schwarze Nekrose erkennbar.": ["Fibrinbelag", "Granulation"],
    "Tiefe, kavitäre Ulzeration mit überwiegend gelblich-cremigem fibrinösem Belag/Slough; stellenweise rötliche Granulationsinseln an der Innenwand; feucht mit dickflüssigem Exsudat; keine freiliegenden Knochen oder Sehnen sichtbar.": ["Exsudat", "Fibrinbelag", "Granulation"],
    "Überwiegend gelblich-weißlicher Fibrin-/Slough-Belag mit einzelnen grau-schwarzen nekrotischen Arealen; randständig geringe rötliche Gewebeanteile; unregelmäßiger, mäßig tiefer Defekt.": ["Fibrinbelag", "Nekrose"],
    "Überwiegend gelb-grauer fibrinöser Slough/Belag, feucht und zäh; kaum sichtbares Granulationsgewebe; unregelmäßig-oval.": ["Fibrinbelag"],
    "Rötliches, feuchtes Granulationsgewebe; teils gelblich fibrinöser Belag randständig; kraterförmiger, tiefer Defekt ohne schwarze Nekrosen; glänzende Oberfläche.": ["Fibrinbelag", "Granulation"],
    "Zwei größere kraterförmige Ulzera mit überwiegend vitaler roter Granulation und teils gelblich-beigen fibrinösen Belägen; feuchtes, glänzendes Wundbett; keine trockene Schwarznekrose sichtbar.": ["Fibrinbelag", "Granulation"],
}


# EXSUDAT MAPPING
EXSUDAT_GT_MAPPING = {
    'Keine': ['Keine'],
    'Leicht': ['Leicht'],
    'Mäßig': ['Mäßig'],
    'Stark': ['Stark'],
    # z.B. "Annahme stark": ["Stark"]
    # ── Allgemeine Grundregeln ──
    "kein": ["Keine"],
    "keine": ["Keine"],
    "trocken": ["Keine"],
    "schwach": ["Leicht"],
    "gering": ["Leicht"],
    "wenig": ["Leicht"],
    "leicht": ["Leicht"],
    "mäßig": ["Mäßig"],
    "mässig": ["Mäßig"],
    "mäfig": ["Mäßig"],
    "mittel": ["Mäßig"],
    "mittelmäßig": ["Mäßig"],
    "mittelmässig": ["Mäßig"],
    "stark": ["Stark"],
    "hoch": ["Stark"],
    "Annahme stark": ["Stark"],

    # ── Einzelwerte ──
    "vermutlich mässig": ["Mäßig"],
    "vermutlich mittelmässig": ["Mäßig"],
    "vermutlich mittelmäßig": ["Mäßig"],
    "vermutlich mäßig": ["Mäßig"],
    "vermutlich mittel": ["Mäßig"],
    "Mässig": ["Mäßig"],
    "scheint mäßig zu sein": ["Mäßig"],
    "wahrscheinlich mittelmäßig vorhanden": ["Mäßig"],
    "nicht genau definierbar, aus der Erfahrung heraus mäßige Exsudation": ["Mäßig"],
    "blutig bis serös teilweise vorhanden dann eher mäßig": ["Mäßig"],
    "vermutlich gering": ["Leicht"],
    "keine Angabe möglich / eher wenig": ["Leicht"],
    "keine Angabe möglich, vermutlich gering": ["Leicht"],
    "vermutlich wenig": ["Leicht"],
    "vermutlich kaum": ["Leicht"],
    "keine Angabe möglich / vermutlich wenig": ["Leicht"],
    "eher weniger": ["Leicht"],
    "eher wenig": ["Leicht"],
    "sehr gering": ["Leicht"],
    "könnte eher schwach sein": ["Leicht"],
    "vermutlich hoch": ["Stark"],
    "nicht beurteilbar, vermutlich stark": ["Stark"],
    "vermutlich hohe Exsudation": ["Stark"],
    "vermutlich starke Exsudation": ["Stark"],
    "mittelstark": ["Stark"],
    "keine Angabe möglich, vermutlich trocken": ["Keine"],
    "keine Angabe möglich / vermutlich mässig": ["Mäßig"],

    # ── Komplexe / Mehrteilige Angaben ──
    "geschlossene stelle kein bis wenig exsudat, offenen stelle mäßig": ["Leicht", "Mäßig"],
    "nekrosen: kein exsudat. unterschenkel mäßig": ["Leicht", "Mäßig"],
    "große wunde: stark, da mazerationen am wundrand kleine nekrose: trocken": ["Mäßig", "Stark"],

    # ── Bereiche ──
    "schwach bis mäßig": ["Leicht", "Mäßig"],
    "schwach bin mäßig": ["Leicht", "Mäßig"],
    "leicht bis mäßig": ["Leicht", "Mäßig"],
    "leichte bis mäßige exsudation": ["Leicht", "Mäßig"],
    "eher schwach b is mäßig": ["Leicht", "Mäßig"],
    "leicht bis mittel": ["Leicht", "Mäßig"],
    "mäßig bis stark": ["Mäßig", "Stark"],
    "mittel bis stark": ["Mäßig", "Stark"],
    "mäßig bis stark, sicher ist eine Geruchsbildung süßlich aromatisch teilweise beschrieben als traubenartig": ["Mäßig", "Stark"],
    "warsch hoch bis sehr hoch,  klare exsudation": ["Stark", "Sehr Stark"],
    "schwach bis nicht vorhanden": ["Keine", "Leicht"],
    "gering bis gar nicht": ["Keine", "Leicht"],
    "keine genaue Angabe möglich, sieht eher trocken bis leicht exsudierend aus": ["Keine", "Leicht"],
}

# WUNDUMGEBUNG MAPPING
WUNDUMGEBUNG_GT_MAPPING = {
    'CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)': ['CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)'],
    'Ekzem / Dermatitis': ['Ekzem / Dermatitis'],
    'Erythem / Rötung': ['Erythem / Rötung'],
    'Mazeration': ['Mazeration'],
    'Reizlos / intakt': ['Reizlos / intakt'],
    'Ödem': ['Ödem'],
    'Sonstiges': ['Sonstiges'],
    # z.B. "Erythem / Rötung": ["Erythem / Rötung"]
}

# WUNDRAND MAPPING
WUNDRAND_GT_MAPPING = {
    'Epibolie (eingerollter Wundrand)': ['Epibolie (eingerollter Wundrand)'],
    'Gerötet / entzündlich': ['Gerötet / entzündlich'],
    'Hyperkeratotisch': ['Hyperkeratotisch'],
    'Mazeriert': ['Mazeriert'],
    'Unterminiert (Wundtaschen)': ['Unterminiert (Wundtaschen)'],
    'Sonstiges': ['Sonstiges'],
    # z.B. "Gerötet / entzündlich": ["Gerötet / entzündlich"]
}

# PRODUKT MAPPING (Präferenz- und Alternativprodukte)
PRODUKT_GT_MAPPING = {
    'Actico UlcerSys System': ['Actico UlcerSys System'],
    'ReadyWrap Untere Extremität': ['ReadyWrap Untere Extremität'],
    'Rosidal TCS': ['Rosidal TCS'],
    'Rosidal soft': ['Rosidal soft'],
    'Suprasorb P SensiFlex multisite border lite': ['Suprasorb P Sensiflex'],
    'Suprasorb P selbstklebend': ['Suprasorb P'],
    'Suprasorb P sensitive (finger/toe)': ['Suprasorb P Sensitive'],
    'Suprasorb P sensitive (sacrum)': ['Suprasorb P Sensitive'],
    'Suprasorb X + PHMB Tamponade': ['Suprasorb X + PHMB'],
    'Vliwasorb sensitive border sacrum': ['Vliwasorb sensitive border'],
    'tg Fertigverbände': ['tg Fertigverbände'],
    'tg Fertigverbände (Hand-/Fußverband)': ['tg Fertigverbände'],
    'tg Fertigverbände Hand-/Fußverband': ['tg Fertigverbände'],
    # ---- Suprasorb A + Ag ----
    "Suprasorb A + Ag": ["Suprasorb A + Ag"],
    "Suprasorb A + Ag (Kompresse)": ["Suprasorb A + Ag"],
    "Suprasorb A + Ag Kompresse": ["Suprasorb A + Ag"],
    "Suprasorb A + Ag Tamponade": ["Suprasorb A + Ag"],

    # ---- Suprasorb A Pro ----
    "Suprasorb A Pro": ["Suprasorb A Pro"],
    "Suprasorb A Pro (Kompresse)": ["Suprasorb A Pro"],
    "Suprasorb A Pro (Tamponade)": ["Suprasorb A Pro"],
    "Suprasorb A Pro Kompresse": ["Suprasorb A Pro"],
    "Suprasorb A Pro Tamponade": ["Suprasorb A Pro"],

    # ---- Suprasorb Liquacel Pro ----
    "Suprasorb Liquacel Pro": ["Suprasorb Liquacel Pro"],
    "Suprasorb Liquacel Pro (Kompresse)": ["Suprasorb Liquacel Pro"],
    "Suprasorb Liquacel Pro (Tamponade)": ["Suprasorb Liquacel Pro"],
    "Suprasorb Liquacel Pro Kompresse": ["Suprasorb Liquacel Pro"],
    "Suprasorb Liquacel Pro Tamponade": ["Suprasorb Liquacel Pro"],

    # ---- Suprasorb P ----
    "Suprasorb P": ["Suprasorb P"],
    "Suprasorb P (nicht klebend)": ["Suprasorb P"],
    "Suprasorb P (selbstklebend)": ["Suprasorb P"],
    "Suprasorb P (self-adhesive, sacrum)": ["Suprasorb P"],
    "Suprasorb P nicht klebend": ["Suprasorb P"],
    "Suprasorb P heel (selbstklebend)": ["Suprasorb P"],

    # ---- Suprasorb P + PHMB ----
    "Suprasorb P + PHMB": ["Suprasorb P + PHMB"],

    # ---- Suprasorb P Sensiflex ----
    "Suprasorb P SensiFlex (border rechteckig)": ["Suprasorb P Sensiflex"],
    "Suprasorb P SensiFlex border": ["Suprasorb P Sensiflex"],
    "Suprasorb P SensiFlex border rechteckig": ["Suprasorb P Sensiflex"],
    "Suprasorb P SensiFlex multisite border": ["Suprasorb P Sensiflex"],
    "Suprasorb P Sensiflex": ["Suprasorb P Sensiflex"],

    # ---- Suprasorb P Sensitive ----
    "Suprasorb P sensitive": ["Suprasorb P Sensitive"],
    "Suprasorb P sensitive (heel)": ["Suprasorb P Sensitive"],
    "Suprasorb P sensitive (nicht klebend)": ["Suprasorb P Sensitive"],
    "Suprasorb P sensitive (selbstklebend)": ["Suprasorb P Sensitive"],
    "Suprasorb P sensitive (selbstklebend) als abdeckender Verband": ["Suprasorb P Sensitive"],
    "Suprasorb P sensitive heel": ["Suprasorb P Sensitive"],
    "Suprasorb P sensitive heel (selbstklebend) – als polsternde, absorbierende Sekundärlage über der Tamponade": ["Suprasorb P Sensitive"],
    "Suprasorb P sensitive sacrum": ["Suprasorb P Sensitive"],
    "Suprasorb P sensitive selbstklebend": ["Suprasorb P Sensitive"],

    # ---- Suprasorb X ----
    "Suprasorb X": ["Suprasorb X"],
    "Suprasorb X Kompresse": ["Suprasorb X"],

    # ---- Suprasorb X Pro ----
    "Suprasorb X Pro": ["Suprasorb X Pro"],
    "Suprasorb X Pro (Kompresse)": ["Suprasorb X Pro"],
    "Suprasorb X Pro Kompresse": ["Suprasorb X Pro"],

    # ---- Suprasorb X + PHMB ----
    "Suprasorb X + PHMB": ["Suprasorb X + PHMB"],
    "Suprasorb X + PHMB (Kompresse)": ["Suprasorb X + PHMB"],
    "Suprasorb X + PHMB Kompresse": ["Suprasorb X + PHMB"],

    # ---- Suprasorb G ----
    "Suprasorb G Gel-Kompresse": ["Suprasorb G Gel-Kompresse"],

    # ---- Suprasorb H ----
    "Suprasorb H": ["Suprasorb H"],

    # ---- Suprasorb F / F Protect ----
    "Suprasorb F": ["Suprasorb F"],
    "Suprasorb F Protect": ["Suprasorb F Protect"],

    # ---- Lomatuell Pro / H ----
    "Lomatuell Pro": ["Lomatuell Pro"],
    "Lomatuell H": ["Lomatuell H"],

    # ---- Vliwasorb Pro / sensitive ----
    "Vliwasorb Pro": ["Vliwasorb Pro"],
    "Vliwasorb sensitive": ["Vliwasorb sensitive"],

    # ---- Vliwazell / Vliwazell Pro ----
    "Vliwazell": ["Vliwazell"],
    "Vliwazell Pro": ["Vliwazell Pro"],
    "Vliwazell Pro als abdeckender Verband": ["Vliwazell Pro"],
    "Vliwazell Pro – als hochabsorbierende Sekundärlage über der Tamponade": ["Vliwazell Pro"],

    # ---- Vliwaktiv Ag ----
    "Vliwaktiv Ag": ["Vliwaktiv Ag"],
    "Vliwaktiv Ag Saugkompresse": ["Vliwaktiv Ag"],
    "Vliwaktiv Ag Tamponade": ["Vliwaktiv Ag"],

    # ---- Solvaline N ----
    "Solvaline N": ["Solvaline N"],

    # ---- Metalline ----
    "Metalline Kompresse": ["Metalline Kompresse"],

    # ---- Curafix / Porofix / Silkafix ----
    "Curafix H": ["Curafix H"],
    "Porofix": ["Porofix"],
    "Silkafix": ["Silkafix"],

    # ---- Mollelast ----
    "Mollelast": ["Mollelast"],
    "Mollelast (Elastische Fixierbinde)": ["Mollelast"],
    "Mollelast haft latexfrei": ["Mollelast haft latexfrei"],

    # ---- Haftelast ----
    "Haftelast latexfrei": ["Haftelast latexfrei"],
    "Haftelast latexfrei (kohäsive Fixierbinde)": ["Haftelast latexfrei"],

    # ---- ActiFast / tg ----
    "ActiFast": ["ActiFast"],
    "ActiFast Schlauchverband": ["ActiFast"],
    "tg Schlauchverband": ["tg Schlauchverband"],

    # ---- Curapor ----
    "Curapor": ["Curapor"],
    "Curapor transparent": ["Curapor transparent"],

    # ---- Sonstige GT-Produkte ----
    "Fixierbinde": ["Fixierbinde"],
    "Fixierbinden": ["Fixierbinde"],
    "Universalbinde": ["Universalbinde"],
    "Universalbinden": ["Universalbinde"],

    # ---- Few-Shot Product Variant Mappings ----
    "Vliwasorb sensitive border": ["Vliwasorb sensitive border"],
    "Vliwasorb sensitive border (sacrum)": ["Vliwasorb sensitive border"],
    "Vliwasorb sensitive border (sacrum)": ["Vliwasorb sensitive border"],
    "Suprasorb P sensitive (Heel, selbstklebend)": ["Suprasorb P Sensitive"],
    "Suprasorb P sensitive (selbstklebend, sacrum)": ["Suprasorb P Sensitive"],
    "Suprasorb P (Heel)": ["Suprasorb P"],
}

# DEBRIDEMENT MAPPING
DEBRIDEMENT_GT_MAPPING = {
    'Autolytisches Debridement': ['Autolytisches Debridement'],
    'Chirurgisches Debridement': ['Chirurgisches Debridement'],
    'Debrisoft Duo': ['Debrisoft Duo'],
    'Debrisoft Lolly': ['Debrisoft Lolly'],
    'Debrisoft Pad': ['Debrisoft Pad'],
    'Ultraschall-assistiertes Debridement (UAW)': ['Ultraschall-assistiertes Debridement (UAW)'],
    # z.B. "Chirurgisches Debridement": ["Chirurgisches Debridement"]
}

# LOKALISATION KEYWORDS
LOKALISATION_KEYWORDS = {
    "Abdomen": ["abdomen", "bauch", "peristom", "stoma"],
    "Fuß": ["fuß", "fuss", "zehe", "ferse", "fußsohle", "fußrücken", "plantar", "vorfuß", "rückfuß", "malleol", "achillessehne", "calcaneus", "hallux", "metatarsal"],
    "Bein": ["bein", "knöchel", "unterschenkel", "oberschenkel", "knie", "gaiter"],
    "Hand": [r"\bhand\b", r"\bhände\b", "finger", "handgelenk", "handrücken"],
    "Arm": ["arm", "ellenbogen", "oberarm", "unterarm", "bizeps", "axilla", "achsel"],
    "Gesäß": ["gesäß", "sakral", "kreuzbein", "steißbein", "os sacrum", "sacral",
              "rima ani", "steiß", "trochanter", "gluteal", "paraglutäal"],
    "Rücken": [r"(?<!fuß)(?<!fuss)(?<!hand)(?<!händ)rücken"],
    "Flanke": ["flanke"],
    "Kopf": [r"\bkopf\b", "hals", "nacken"],
    "Brust": ["brust", "thorax"]
}
