SPELLING_MAPPING = {
    "ulcus": "ulkus",
    "decubitus": "dekubitus",
}

WUNDTYP_GT_MAPPING = {
    'Ausgedehnte feuchte Nekrose': ['Ausgedehnte feuchte Nekrose'],
    'Ausgetrtenes Blut oder Lymphe aus den entsprechenden Gefäßen mit Verteilung an der betroffenen Extremität': ['Ulkus (Ätiologie unspezifisch)'],
    'Dekubitus': ['Dekubitus'],
    'Dekubitus Grad 2 oder 3 nach EPUAP.\nNicht genau zu definieren, ob sich Unterminierungen vorhanden sind.': ['Dekubitus'],
    'Dekubitus an der Ferse': ['Dekubitus'],
    'Dekubitus epuap Stadium 3 / 4': ['Dekubitus'],
    'Dekubitus mit Nekrose': ['Dekubitus'],
    'Dekubitus mit Taschenbildung': ['Dekubitus'],
    'Dekubitus sacralbereich': ['Dekubitus'],
    'Dekubitus, vermutlich am Außenknöchel': ['Dekubitus'],
    'Dekubtis im Sakralbereich, großflächig': ['Dekubitus'],
    'Fersendekubitus': ['Dekubitus'],
    'Fersenulcus / eventuell Mischulcus': ['Ulcus cruris mixtum'],
    'Fibrinbelegtes Ulcus': ['Ulkus (Ätiologie unspezifisch)'],
    'Fibringbelegtes Ulcus': ['Ulkus (Ätiologie unspezifisch)'],
    'Hypergranulation nach Verbrennung': ['Verbrennungswunde'],
    'Hämangiom ist ein Spezialgebiet. In der Regel ist dieses innerhalb des ersten Lebensjahres rückläufig.\nDeshalb nehme ich hier keine Beurteilung vor.': ['Hämangiom ist ein Spezialgebiet. In der Regel ist dieses innerhalb des ersten Lebensjahres rückläufig.\nDeshalb nehme ich hier keine Beurteilung vor.'],
    'Infizierte Wunden am linken Oberarm / Innenseitig': ['Infizierte Wunden am linken Oberarm / Innenseitig'],
    'Infiziertes Ulcus mit freiliegender Sehne': ['Ulkus (Ätiologie unspezifisch)'],
    'Oberflächliches Ulcus': ['Ulkus (Ätiologie unspezifisch)'],
    'Oberflächliches Ulcus (diffuse Defekte)': ['Ulkus (Ätiologie unspezifisch)'],
    'Plantares Ulcus linker Fuß, Ursachen Klärung notwendig, bei Diabetiker Prüfung ob Neuropathisch oder Angiopathische Ursache': ['Plantares Ulcus linker Fuß, Ursachen Klärung notwendig, bei Diabetiker Prüfung ob Neuropathisch oder Angiopathische Ursache'],
    'Platzbauch nach möglichem chirurgischen Eingriff': ['Postoperative Wunde / Dehiszenz'],
    'Postoperative Wunde abdominal': ['Postoperative Wunde / Dehiszenz'],
    'Taschenbildendes Ulcus am linken Fußrücken': ['Ulkus (Ätiologie unspezifisch)'],
    'Teils nekrotisches Ulcus an der linken Ferse.\nplantares Ulcus belegt mit Infektionszeichen': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcera rechter Fuß. könnte ursächlich diabetischer Fuß sein ( Neuropathie, Angiopathie) oder arterielles ulcus schäden auf Grund fehlender Durchblutung': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcerationen bedingt durch Vaskulitis- Form der rheumatischen Erkrankung ( Autoimmunerkrankung)': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus / warsch. Ulcus cruris, Ursache nicht klar, muss bestimmt werden': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus Dekubitus': ['Dekubitus'],
    'Ulcus Dekubitus Bereich OS Sacrum': ['Dekubitus'],
    'Ulcus Dekubitus Epuap Grad 3 / 4': ['Dekubitus'],
    'Ulcus Dekubitus nach Epuap Grad 2 bis 3': ['Dekubitus'],
    'Ulcus Ursache nicht genau definierbar': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus am Fussrücken': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus am Unterschenkel medial': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus an der Achillessehne': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus auf Grund von Mangeldurchblutung. Könnte diabetischer Fuß sein / angiopathisch bedingt.': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus auf Grund von Mangelernährung des Gewebes, Druckschäden in Kombination mit Gefäßschäden': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus cruris': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus cruris  unklarer Ursache': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus cruris /  Gravitationsulcus: Ulcus cruris venosum': ['Ulcus cruris venosum'],
    'Ulcus cruris li lateraler Malleolus': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus cruris möglich arteriell oder mixtum': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus cruris venosum': ['Ulcus cruris venosum'],
    'Ulcus decubitus': ['Dekubitus'],
    'Ulcus decubitus Nach Epuap Grad 2 bis 3': ['Dekubitus'],
    'Ulcus dekubitus': ['Dekubitus'],
    'Ulcus dekubitus Ferse,  Stadium 3 / 4': ['Dekubitus'],
    'Ulcus lokal abgegrenzt. belegt könnte ebenso nekrotisch sein': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus mit Stauung': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus mit scheinender Hypergranulation oberhalb der Achillessehne': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus nach Meshgraft (zumindest lässt die Struktur darauf schließen), eventuell ist die Struktur aber einer Unterdrucktherapie geschuldet': ['Postoperative Wunde / Dehiszenz'],
    'Ulcus nach Stich': ['Traumatische Wunde'],
    'Ulcus unbekannter Herkunft, könnte traumatologisch bedingte Wunde sein, durch die Wunde bei unsachgemäßer Versorgung entstehen ulcerationen ebenfalls, nicht immer Krankheitsbedingt': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus unklarer Genese': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus unklarer Genese am Bein genaue Lokalisation nicht beurteilbar': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus unklarer Genese, könnte Venös oder arteriell oder mixum sein.\nBeachte kleine Nekrose an der Ferse plantar': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus unklarer Genese, könnte diabet. Ulcus sein, möglich ebenso durch traumatologische Ursachen': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus, Lokalisation am Bein nicht genau definierbar': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus, bei vermutetem Diabetes': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus, durch die Mangelernährung ( keine Durchblutung) im Wundgebiet  könnte es sich um einen Dekubitus oder ulcus cruris handeln.': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulcus. Ursache klären sollte es ein diabet. Fuß sein dann Prüfung ob angiopathisch oder neuropathisch,\nDruckentlastung und Ursachenbeseitigung.': ['Ulkus (Ätiologie unspezifisch)'],
    'Ulkus Dekubitus am Os sacrum  nach Epuap Grad 2 / 3': ['Dekubitus'],
    'Ulkus an der Ferse, warsch. Dekubitus nach EPUAP  Stadium 3': ['Dekubitus'],
    'Verbrennung 2 und 3 Grades nach 9 er Regel etwa 9 % Körperoberfläche': ['Verbrennungswunde'],
    'Verbrennung 2. Grades am Bein': ['Verbrennungswunde'],
    'Verbrennung 2. und teilweise 3. Grades Oberfläche ca 9 %': ['Verbrennungswunde'],
    'Verbrennung Grad 1 bis 2 am rechten Fuß': ['Verbrennungswunde'],
    'Verbrennungswunde 1. bis 2. Grades': ['Verbrennungswunde'],
    'Verbrennungswunde am Arm Grad 2': ['Verbrennungswunde'],
    'Wunde am li Fußrücken mit Sehnenfreilegung': ['Wunde am li Fußrücken mit Sehnenfreilegung'],
    'Wunde aufgrund einer Infusion, welche ins umliegende Gewebe ausgetreten ist': ['Wunde aufgrund einer Infusion, welche ins umliegende Gewebe ausgetreten ist'],
    '["Dekubitus","Diabetisches Fußulkus"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["Dekubitus","Ulcus"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["Dekubitus"]': ['Dekubitus'],
    '["Diabetisches Fußulkus","hochgradig destruierende Fußwunde"]': ['Diabetisches Fußsyndrom (DFS)'],
    '["Diabetisches Fußulkus","ischämisches Ulkus"]': ['Diabetisches Fußsyndrom (DFS)'],
    '["Diabetisches Fußulkus","mit deutlichen Zeichen einer lokalen Infektion und chronisch entzündlicher Hautveränderungen"]': ['Diabetisches Fußsyndrom (DFS)'],
    '["Diabetisches Fußulkus"]': ['Diabetisches Fußsyndrom (DFS)'],
    '["Extravasationsverletzung"]': ['Extravasationsverletzung'],
    '["Gravitationsulzera/Druckulzera"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["Postoperative Wunde"]': ['Postoperative Wunde / Dehiszenz'],
    '["Traumatische Wunde","durch Insektenstich"]': ['Traumatische Wunde'],
    '["Ulcus Fußrücken mit deutlicher Gewebedestruktion und freiliegender Sehnenstruktur"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["Ulcus cruris venosum","Adipositas-assoziiert"]': ['Ulcus cruris venosum'],
    '["Ulcus cruris venosum","venös-lymphatischem Ulcus"]': ['Ulcus cruris venosum'],
    '["Ulcus cruris venosum"]': ['Ulcus cruris venosum'],
    '["Ulcus"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["Ulkus cruris"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["Ulkus"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["Verbrennungswunde"]': ['Verbrennungswunde'],
    '["ausgedehnte, tiefe, nekrotische Ulzeration"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["ausgedehntes, tiefes chronisches Ulcus"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["ausgeprägtes infiziertes Ulcus cruris","Ulcus cruris venosum"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["chronische Fußwunde / Ulkus"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["chronisches Ulkus cruris"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["chronisches Ulkus"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["großflächiges, flaches chronisches Ulkus"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["kleines, oberflächliches Ulcus"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["multiple infizierte chronische Fußulzera"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["multiple kleine Ulzera"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["nekrotische Fersenwunde","Dekubitus"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["nekrotische ischämische Fußwunde / Gangrän"]': ['Ulcus cruris arteriosum / Ischämisches Ulkus'],
    '["neuroischämisches bzw. arterielles Fußulkus"]': ['Ulcus cruris arteriosum / Ischämisches Ulkus'],
    '["rundlich-ovales Ulcus"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["tiefer reichende Ulzerationen am Unterschenkel mit chronisch entzündlicher Umgebung"]': ['Ulkus (Ätiologie unspezifisch)'],
    '["ulzeriertes infantiles Hämangiom mit zentraler Nekrose"]': ['ulzeriertes infantiles Hämangiom mit zentraler Nekrose'],
    '["vaskulitischen Ulzera","möglicher kutaner Vaskulitis"]': ['Ulkus (Ätiologie unspezifisch)'],
    'arterielles Ulcus': ['Ulcus cruris arteriosum / Ischämisches Ulkus'],
    'belegter Ulcus': ['Ulkus (Ätiologie unspezifisch)'],
    'diffuse fibrinbelegte und teils infizierte Ulzera am rechten Fuß': ['Ulkus (Ätiologie unspezifisch)'],
    'fibrinbelegtes Ulcus': ['Ulkus (Ätiologie unspezifisch)'],
    'gleiche Beurteilung wie Wunde 53': ['Dekubitus'],
    'infantiles Hämangiom,': ['infantiles Hämangiom,'],
    'könnte arterieller Ulcus oder diabetischer Ulcus ( Angiopathie) auf Grund der Mangeldurchblutung  sein.': ['Ulkus (Ätiologie unspezifisch)'],
    'könnte diabetischer ulcus sein auf grund einer neuropathie': ['Ulkus (Ätiologie unspezifisch)'],
    'könnte ein diabetischer Fuß sein, Ulcus  nicht möglich,\ntraumatologische Indikation ebenso nicht ausgeschlossen': ['Ulkus (Ätiologie unspezifisch)'],
    'laterales Ulcus linker Fuß': ['Ulkus (Ätiologie unspezifisch)'],
    'massives Ulcus dekubitus': ['Dekubitus'],
    'mumifizierte Zehen (D4 und D5), gleichzeitig Nekrose an der rechten Ferse': ['Ulcus cruris arteriosum / Ischämisches Ulkus'],
    'möglicherweise ein feuchtes Gangrän': ['Ulcus cruris arteriosum / Ischämisches Ulkus'],
    'nekrotischen Wunden am Fuß': ['nekrotischen Wunden am Fuß'],
    'nekrotischer Defekt / Dekubitus': ['Dekubitus'],
    'nekrotischer Dekubitus li Ferse': ['Dekubitus'],
    'oberflächlicher Dekubitus ( 2 Stück)': ['Dekubitus'],
    'oberflächliches Ulcus': ['Ulkus (Ätiologie unspezifisch)'],
    'offene ulcera': ['Ulkus (Ätiologie unspezifisch)'],
    'plantares ulcus': ['Ulkus (Ätiologie unspezifisch)'],
    'pseudomas besiedeltes teils nekrotisches Ulcus.\nSemizirkulär': ['Ulkus (Ätiologie unspezifisch)'],
    'rechter Fuß lateral/ malleolär': ['rechter Fuß lateral/ malleolär'],
    'schwere Nekrose am Fuß rechts lateral und plantar, offene Geschwüre über den Malleolen lateral\ndeutet auf arterielles Ulcus hin': ['Ulcus cruris arteriosum / Ischämisches Ulkus'],
    'schwere Ulzerationen am Fuß- mehrere offene Stellen, freiliegende Sehen, teilweise nekrotisch, belegt': ['Ulkus (Ätiologie unspezifisch)'],
    'semizirkuläres Ulcus': ['Ulkus (Ätiologie unspezifisch)'],
    'semizirkuläres Ulcus re Fuß': ['Ulkus (Ätiologie unspezifisch)'],
    'superinfizierte Ulcration am rechen Fuß offene Ulcera': ['Ulkus (Ätiologie unspezifisch)'],
    'tiefer Dekubitus': ['Dekubitus'],
    'tiefes Ulcus im Fersenbereich': ['Ulkus (Ätiologie unspezifisch)'],
    'traumatologische Wunde ( thermische Schädigung / Verbrennung 3. und 4. Grades': ['Verbrennungswunde'],
    'ulcus cruris': ['Ulkus (Ätiologie unspezifisch)'],
    'vermutlich Mischulcus am rechten Bein, höhe der Knöchel.\nSemizirkulär': ['Ulcus cruris mixtum'],
    'zirkuläres Ulcus Unterschenkel (vermutlich Mischulcus)': ['Ulcus cruris mixtum'],
}

LOKALISATION_GT_MAPPING = {
    '...stark exsudierendes, nekrotisch belegtes Ulcus mit grünlicher Verfärbung typisch für Pseudomonas aeruginosa.': ['Enthaltung / keine Angabe'],
    '?': ['Enthaltung / keine Angabe'],
    '???': ['Enthaltung / keine Angabe'],
    'Abdomen': ['Abdomen'],
    'Abdomen, links': ['Abdomen'],
    'Arm': ['Arm / Hand'],
    'Arm oder Bein??': ['Enthaltung / keine Angabe'],
    'Aussenseitig linke Fußsohle': ['Fuß'],
    'Außenknöchel links': ['Fuß'],
    'Bein': ['Bein'],
    'Bein nicht genau definierbar': ['Bein'],
    'Bein wo genau fraglich': ['Bein'],
    'Bein, Unterschenkel Richtung Fuß': ['Bein'],
    'Bein, evtl. links, Unterschenkel': ['Bein'],
    'Bein, evtl. rechts, Unterschenkel': ['Bein'],
    'Bein, genaue Definition nicht möglich': ['Bein'],
    'Bein, genauere Lokalisation nicht genau definierbar': ['Bein'],
    'Bein, wo genau nicht definierbar': ['Bein'],
    'Das Bild zeigt ein großflächiges venöses Ulcus cruris bei ausgeprägter chronisch venöser Stauung und Adipositas-assoziierter Belastung. Möglich, Oberschenkel links, Unterschenkel': ['Bein'],
    'Ferse': ['Fuß'],
    'Ferse, Achillessehne': ['Fuß'],
    'Ferse, linker Fuß': ['Fuß'],
    'Ferse, rechter Fuß': ['Fuß'],
    'Ferse, scheint links zu sein:\ngelblich-fibrinösem Belag\nmäßiger Exsudation\ngerötetem Wundrand': ['Fuß'],
    'Fuß lateral links': ['Fuß'],
    'Fuß links plantar': ['Fuß'],
    'Fuß links plantar  lateral': ['Fuß'],
    'Fuß rechts': ['Fuß'],
    'Fuß, Ferse links': ['Fuß'],
    'Fußrücken': ['Fuß'],
    'Fußrücken linker Fuß': ['Fuß'],
    'Fußrücken rechter Fuß': ['Fuß'],
    'Fußsohle Ferse': ['Fuß'],
    'Gesäß-/Sakralregion': ['Gesäß / Sakral'],
    'Gesäß-/perianale Region eines Säuglings': ['Gesäß / Sakral'],
    'Knöchelinnenseite': ['Fuß'],
    'Lokalisation: Fußrücken, lateraler Vorfuß sowie Zehenbereiche': ['Fuß'],
    'Lokalisation: Unterschenkelbereich': ['Bein'],
    'Lokalisation: Unterschenkelregion': ['Bein'],
    'Lokalisation: lateraler Mittelfuß/Knöchelbereich': ['Fuß'],
    'Lokalisation: lateraler Vor-/Mittelfuß': ['Fuß'],
    'Lokalisation: sakrogluteale/perianale Region beidseits': ['Gesäß / Sakral'],
    'Lokalisation: vermutlich Sakral-/Gesäßregion': ['Gesäß / Sakral'],
    'Oberarb Muskulus bizeps': ['Arm / Hand'],
    'Os Sacrum': ['Gesäß / Sakral'],
    'Rima Ani': ['Gesäß / Sakral'],
    'Sakralbereich': ['Gesäß / Sakral'],
    'Sakralbereich linke hälfte': ['Gesäß / Sakral'],
    'Sakraler Bereich': ['Gesäß / Sakral'],
    'Steiß': ['Gesäß / Sakral'],
    'Unterarm': ['Arm / Hand'],
    'Unterschenkel': ['Bein'],
    'Unterschenkel  medial': ['Bein'],
    'Unterschenkel warsch. gamaschenartig / bereits zirkulierend': ['Bein'],
    'Unterschenkel weit umfassend': ['Bein'],
    'Unterschenkel, Außenseite auf Knie Höhe': ['Bein'],
    'Unterschenkel, rechts, Innenseite': ['Bein'],
    'Unterschenkel/Knöchelregion, zirkumferenziell ausgedehnt': ['Bein'],
    'Unterschenkel?': ['Bein'],
    'chronisches Ulkus im Bereich der Achillessehne\ndorsaler Unterschenkel / Achillessehnenregion': ['Bein'],
    'ferse, fußsohle': ['Fuß'],
    'fibrinösem gelblich-weißem Belag,\nmäßiger Exsudation,\ngerötetem Wundrand,\n--> vermutlich entzündlicher bzw. kritisch kolonisierter Situation,': ['Enthaltung / keine Angabe'],
    'größeres, flächiges Ulcus am Unterschenkel (Wade) bei ausgeprägtem Ödem und Adipositas-assoziierter Hautveränderung.': ['Bein'],
    'keine Angabe möglich': ['Enthaltung / keine Angabe'],
    'könnte Innenseite linker Fuß sein': ['Fuß'],
    'könnte Unterschenkel oder Handgelenk sein': ['Enthaltung / keine Angabe'],
    'könnte am linken Fuß sein... Knöchelbereich': ['Fuß'],
    'könnte der Unterschenkel sein, rechts': ['Bein'],
    'könnte oberhalb des os sacrum liegen': ['Gesäß / Sakral'],
    'könnte sich im Bereich des Steißes befinden': ['Gesäß / Sakral'],
    'lateral linker Fuß': ['Fuß'],
    'li lateraler Malleolus': ['Fuß'],
    'li. Fußrücken': ['Fuß'],
    'linke Ferse': ['Fuß'],
    'linker Fuss': ['Fuß'],
    'linker Fussrücken': ['Fuß'],
    'linker Fuß': ['Fuß'],
    'linker Fuß\nLokalisation: dorsaler und lateraler Vorfuß mit Beteiligung der Zehenbasis': ['Fuß'],
    'linker Fuß - dorsaler Vorfuß/Fußrücken': ['Fuß'],
    'linker Fuß außen': ['Fuß'],
    'linker Fuß lateratl': ['Fuß'],
    'linker Fuß medial, malleolär': ['Fuß'],
    'linker Fuß medial-lateral \nkleine Nekrose an der Ferse außen plantar': ['Fuß'],
    'linker Fuß, Außenseite': ['Fuß'],
    'linker Fuß, Ferse': ['Fuß'],
    'linker Fuß, Innenseite': ['Fuß'],
    'linker Fuß, Mittelfußsohle, Ferse': ['Fuß'],
    'linker Fuß, Spann, Fußrücken': ['Fuß'],
    'linker Fuß, außenseite': ['Fuß'],
    'linker Fuß, seite': ['Fuß'],
    'linker Fußrücken': ['Fuß'],
    'linker Oberarm, Innenseite': ['Arm / Hand'],
    'linker Oberarm/ Innenseitig': ['Arm / Hand'],
    'linker proximaler Unterschenkel lateral': ['Bein'],
    'linkes Bein unterhalb Knie lateral': ['Bein'],
    'lokalisation nicht genau zu definieren': ['Enthaltung / keine Angabe'],
    'mediale Fußseite linker Fuß': ['Fuß'],
    'mehrere kleine bis mittelgroße Ulzerationen am Unterschenkel (Wade, rechts?) mit entzündlich wirkender Umgebungshaut.': ['Bein'],
    'multiple Schädigung gesamter Gesäßbereich': ['Gesäß / Sakral'],
    'nicht beurteilbar': ['Enthaltung / keine Angabe'],
    'nicht genau definierbar': ['Enthaltung / keine Angabe'],
    'nicht genau definierbar könnte Sakralbereich sein': ['Gesäß / Sakral'],
    'nicht genau definierbar sieht für mich aus wie am Vorfuß': ['Fuß'],
    'nicht genau definierbar, Vermutung Unterschenkel': ['Bein'],
    'nicht genau definierbar, meist am Unterschenkel': ['Bein'],
    'oberhalb der Achillessehne': ['Fuß'],
    'plantarseitig rechter Fuß': ['Fuß'],
    're Fuß': ['Fuß'],
    'rechte Ferse': ['Fuß'],
    'rechte Hand': ['Arm / Hand'],
    'rechte Hand und Arm': ['Arm / Hand'],
    'rechter Fuß': ['Fuß'],
    'rechter Fuß - lateraler und plantarer Fußbereich/Ferse': ['Fuß'],
    'rechter Fuß Fußrücken und lateral': ['Fuß'],
    'rechter Fuß medial, Richtung plantar.': ['Fuß'],
    'rechter Fuß plantar': ['Fuß'],
    'rechter Fuß, Ferse': ['Fuß'],
    'rechter Fuß, Ferse, Mittelfuß - Fußsohle': ['Fuß'],
    'rechter Fuß, Fußsohle': ['Fuß'],
    'rechter Fuß, Innenseite, Knöchel': ['Fuß'],
    'rechter Fuß, Spann': ['Fuß'],
    'rechter Fuß, in Höhe der großen Zehe, unterhalb der medialen Malleolen': ['Fuß'],
    'rechter Unterarm, rechtes Handgelenk, rechte Hand': ['Arm / Hand'],
    'rechter Unterschenkel': ['Bein'],
    'rechtes Bein, Kniebereich, Unterschenkel': ['Bein'],
    'rechtes Bein, höhe der Knöchel': ['Bein'],
    'sacralbereich': ['Gesäß / Sakral'],
    'sakrales Dekubitalulkus': ['Gesäß / Sakral'],
    'schwer zu beurteilen, Vermutung am Trochanter major': ['Bein'],
    'schwer zu beurteilen, keine genaue Angabe möglich,\neventuell Rücken Richtung Oberarm /': ['Enthaltung / keine Angabe'],
    'schwierig zu beantworten... könnte die Wade sein, evtl. rechts': ['Bein'],
    'unterschenkel': ['Bein'],
    'vermutlich am Außenknöchel': ['Fuß'],
    'vermutlich am Unterschenkel': ['Bein'],
}

EXSUDAT_GT_MAPPING = {
    'Annahme stark': ['Stark'],
    'Große Wunde: stark, da Mazerationen am Wundrand\nKleine Nekrose: trocken': ['Stark'],
    'Keine': ['Keine'],
    'Leicht': ['Leicht'],
    'Mässig': ['Mäßig'],
    'Mäßig': ['Mäßig'],
    'Nekrosen: kein Exsudat. Unterschenkel mäßig': ['Mäßig'],
    'Stark': ['Stark'],
    'blutig bis serös teilweise vorhanden dann eher mäßig': ['Mäßig'],
    'eher schwach b is mäßig': ['Leicht', 'Mäßig'],
    'eher wenig': ['Leicht'],
    'eher weniger': ['Leicht'],
    'gering bis gar nicht': ['Keine', 'Leicht'],
    'kein': ['Keine'],
    'keine': ['Keine'],
    'keine Angabe möglich': ['Enthaltung / keine Angabe'],
    'keine Angabe möglich / eher wenig': ['Leicht'],
    'keine Angabe möglich / vermutlich mässig': ['Mäßig'],
    'keine Angabe möglich / vermutlich wenig': ['Leicht'],
    'keine Angabe möglich, vermutlich gering': ['Leicht'],
    'keine Angabe möglich, vermutlich trocken': ['Keine'],
    'keine Einschätzung möglich': ['Enthaltung / keine Angabe'],
    'keine genaue Angabe möglich, sieht eher trocken bis leicht exsudierend aus': ['Keine', 'Leicht'],
    'könnte eher schwach sein': ['Leicht'],
    'leicht': ['Leicht'],
    'leicht bis mittel': ['Leicht', 'Mäßig'],
    'leicht bis mäßig': ['Leicht', 'Mäßig'],
    'leichte bis mäßige exsudation': ['Leicht', 'Mäßig'],
    'mittel': ['Mäßig'],
    'mittel bis stark': ['Mäßig', 'Stark'],
    'mittelstark': ['Mäßig'],
    'mäfig': ['Mäßig'],
    'mäßig': ['Mäßig'],
    'mäßig bis stark': ['Mäßig', 'Stark'],
    'mäßig bis stark, sicher ist eine Geruchsbildung süßlich aromatisch teilweise beschrieben als traubenartig': ['Mäßig', 'Stark'],
    'nicht beurteilbar': ['Enthaltung / keine Angabe'],
    'nicht beurteilbar, vermutlich stark': ['Stark'],
    'nicht genau definierbar, aus der Erfahrung heraus mäßige Exsudation': ['Mäßig'],
    'nicht klar, eher trübe Wunde könnte Geruch abgeben': ['Enthaltung / keine Angabe'],
    'nicht zu beschreiben': ['Enthaltung / keine Angabe'],
    'offenen stelle mäßig, geschlossene stelle kein bis wenig exsudat': ['Keine', 'Leicht'],
    'scheint mäßig zu sein': ['Mäßig'],
    'schwach': ['Leicht'],
    'schwach bin mäßig': ['Leicht', 'Mäßig'],
    'schwach bis mäßig': ['Leicht', 'Mäßig'],
    'schwach bis nicht vorhanden': ['Keine', 'Leicht'],
    'sehr gering': ['Leicht'],
    'stark': ['Stark'],
    'vermutlich gering': ['Leicht'],
    'vermutlich hoch': ['Stark'],
    'vermutlich hohe Exsudation': ['Stark'],
    'vermutlich kaum': ['Keine'],
    'vermutlich mittel': ['Mäßig'],
    'vermutlich mittelmässig': ['Mäßig'],
    'vermutlich mittelmäßig': ['Mäßig'],
    'vermutlich mässig': ['Mäßig'],
    'vermutlich mäßig': ['Mäßig'],
    'vermutlich starke Exsudation': ['Stark'],
    'vermutlich vorhanden, in welcher Menge ist nicht zu beurteilen': ['Enthaltung / keine Angabe'],
    'vermutlich wenig': ['Leicht'],
    'wahrscheinlich mittelmäßig vorhanden': ['Mäßig'],
    'warsch hoch bis sehr hoch,  klare exsudation': ['Stark'],
}

WUNDUMGEBUNG_GT_MAPPING = {
    '["CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)","Erythem / Rötung"]': ['CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)', 'Erythem / Rötung'],
    '["CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)"]': ['CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)'],
    '["Ekzem / Dermatitis","Erythem / Rötung"]': ['Ekzem / Dermatitis', 'Erythem / Rötung'],
    '["Ekzem / Dermatitis"]': ['Ekzem / Dermatitis'],
    '["Erythem / Rötung","CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)"]': ['CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)', 'Erythem / Rötung'],
    '["Erythem / Rötung","Ekzem / Dermatitis","CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)"]': ['CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)', 'Ekzem / Dermatitis', 'Erythem / Rötung'],
    '["Erythem / Rötung","Ekzem / Dermatitis"]': ['Ekzem / Dermatitis', 'Erythem / Rötung'],
    '["Erythem / Rötung","Mazeration","CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)"]': ['CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)', 'Erythem / Rötung', 'Mazeration'],
    '["Erythem / Rötung","Mazeration"]': ['Erythem / Rötung', 'Mazeration'],
    '["Erythem / Rötung","Weichteilreizung"]': ['Erythem / Rötung'],
    '["Erythem / Rötung","deutliche entzündliche Rötung der Umgebung"]': ['Erythem / Rötung'],
    '["Erythem / Rötung","eher trocken wirkende Umgebung"]': ['Erythem / Rötung'],
    '["Erythem / Rötung","entzündliche Umgebungshaut"]': ['Erythem / Rötung'],
    '["Erythem / Rötung","leicht gerötete, glänzende Umgebungshaut"]': ['Erythem / Rötung'],
    '["Erythem / Rötung","Ödem","CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)"]': ['CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)', 'Erythem / Rötung', 'Ödem'],
    '["Erythem / Rötung","Ödem"]': ['Erythem / Rötung', 'Ödem'],
    '["Erythem / Rötung"]': ['Erythem / Rötung'],
    '["Keratosen"]': ['Sonstiges'],
    '["Mazeration","Erythem / Rötung","trockener wirkende Areale mit verminderter Durchblutung"]': ['Erythem / Rötung', 'Mazeration'],
    '["Mazeration","Erythem / Rötung"]': ['Erythem / Rötung', 'Mazeration'],
    '["Mazeration","glänzend"]': ['Mazeration'],
    '["Mazeration","glänzende, gespannte Umgebungshaut"]': ['Mazeration'],
    '["Mazeration"]': ['Mazeration'],
    '["Reizlos / intakt","Erythem / Rötung"]': ['Erythem / Rötung', 'Reizlos / intakt'],
    '["Reizlos / intakt"]': ['Reizlos / intakt'],
    '["atrophisch-trockene Haut mit trophischen Störungen","CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)"]': ['CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)'],
    '["empfindliche Säuglingshaut mit hoher Feuchtigkeits- und Reibungsbelastung"]': ['Sonstiges'],
    '["fragile, atrophe Haut"]': ['Sonstiges'],
    '["gerötet-glänzende Haut, Hinweis auf chronische venöse Stauung/Ödemneigung"]': ['Erythem / Rötung', 'Ödem'],
    '["gerötet-glänzende, ödematöse Haut","Erythem / Rötung"]': ['Erythem / Rötung', 'Ödem'],
    '["gut durchbluteter, überwiegend roter Wundgrund"]': ['Reizlos / intakt'],
    '["rocken, teils schuppig, gespannt"]': ['Sonstiges'],
    '["zahlreiche erythematöse Makulae/Papeln, livid-entzündliche Hautveränderungen, Hinweis auf entzündlich-vaskulären Prozess"]': ['Ekzem / Dermatitis', 'Erythem / Rötung'],
    '["Ödem","CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)"]': ['CVI-typische Hautveränderungen (Hyperpigmentierung, Atrophie blanche, Lipodermatosklerose)', 'Ödem'],
    '["Ödem","Erythem / Rötung"]': ['Erythem / Rötung', 'Ödem'],
    '["Ödem","gespannte, trophisch veränderte Haut"]': ['Ödem'],
    '["Ödem"]': ['Ödem'],
    '[]': [],
}

WUNDRAND_GT_MAPPING = {
    '["Epibolie (eingerollter Wundrand)","Gerötet / entzündlich","Mazeriert"]': ['Epibolie (eingerollter Wundrand)', 'Gerötet / entzündlich', 'Mazeriert'],
    '["Epibolie (eingerollter Wundrand)","Gerötet / entzündlich"]': ['Epibolie (eingerollter Wundrand)', 'Gerötet / entzündlich'],
    '["Epibolie (eingerollter Wundrand)","Mazeriert"]': ['Epibolie (eingerollter Wundrand)', 'Mazeriert'],
    '["Epibolie (eingerollter Wundrand)"]': ['Epibolie (eingerollter Wundrand)'],
    '["Gelbliche fibrinöse Randbeläge"]': [],
    '["Gerötet / entzündlich","Epibolie (eingerollter Wundrand)"]': ['Epibolie (eingerollter Wundrand)', 'Gerötet / entzündlich'],
    '["Gerötet / entzündlich","Mazeriert","Unterminiert (Wundtaschen)"]': ['Gerötet / entzündlich', 'Mazeriert', 'Unterminiert (Wundtaschen)'],
    '["Gerötet / entzündlich","Mazeriert"]': ['Gerötet / entzündlich', 'Mazeriert'],
    '["Gerötet / entzündlich","Taschenbildung möglich"]': ['Gerötet / entzündlich', 'Unterminiert (Wundtaschen)'],
    '["Gerötet / entzündlich","Unterminiert (Wundtaschen)"]': ['Gerötet / entzündlich', 'Unterminiert (Wundtaschen)'],
    '["Gerötet / entzündlich","glänzende, ödematöse Haut"]': ['Gerötet / entzündlich'],
    '["Gerötet / entzündlich","livid-erythematöse Hautveränderungen"]': ['Gerötet / entzündlich'],
    '["Gerötet / entzündlich","relativ scharf begrenzte Wundränder"]': ['Gerötet / entzündlich'],
    '["Gerötet / entzündlich","unregelmäßige Wundränder"]': ['Gerötet / entzündlich'],
    '["Gerötet / entzündlich","unregelmäßigen Rändern"]': ['Gerötet / entzündlich'],
    '["Gerötet / entzündlich"]': ['Gerötet / entzündlich'],
    '["Hyperkeratotisch","Gerötet / entzündlich"]': ['Gerötet / entzündlich', 'Hyperkeratotisch'],
    '["Hyperkeratotisch"]': ['Hyperkeratotisch'],
    '["Mazeriert","Epibolie (eingerollter Wundrand)","Gerötet / entzündlich"]': ['Epibolie (eingerollter Wundrand)', 'Gerötet / entzündlich', 'Mazeriert'],
    '["Mazeriert","Epibolie (eingerollter Wundrand)"]': ['Epibolie (eingerollter Wundrand)', 'Mazeriert'],
    '["Mazeriert","Gerötet / entzündlich","Epibolie (eingerollter Wundrand)"]': ['Epibolie (eingerollter Wundrand)', 'Gerötet / entzündlich', 'Mazeriert'],
    '["Mazeriert","Gerötet / entzündlich","Unterminiert (Wundtaschen)"]': ['Gerötet / entzündlich', 'Mazeriert', 'Unterminiert (Wundtaschen)'],
    '["Mazeriert","Gerötet / entzündlich"]': ['Gerötet / entzündlich', 'Mazeriert'],
    '["Mazeriert","Unterminiert (Wundtaschen)","Gerötet / entzündlich"]': ['Gerötet / entzündlich', 'Mazeriert', 'Unterminiert (Wundtaschen)'],
    '["Mazeriert","Unterminiert (Wundtaschen)"]': ['Mazeriert', 'Unterminiert (Wundtaschen)'],
    '["Mazeriert","teilweise aufgequollen"]': ['Mazeriert'],
    '["Mazeriert"]': ['Mazeriert'],
    '["Reizlos / unauffällig"]': ['Reizlos / unauffällig'],
    '["Unterminiert (Wundtaschen)","Epibolie (eingerollter Wundrand)"]': ['Epibolie (eingerollter Wundrand)', 'Unterminiert (Wundtaschen)'],
    '["Unterminiert (Wundtaschen)","Gerötet / entzündlich"]': ['Gerötet / entzündlich', 'Unterminiert (Wundtaschen)'],
    '["Unterminiert (Wundtaschen)","Mazeriert"]': ['Mazeriert', 'Unterminiert (Wundtaschen)'],
    '["Unterminiert (Wundtaschen)"]': ['Unterminiert (Wundtaschen)'],
    '["scharf begrenzt, teils livide/verfärbt, ischämietypisch"]': ['Reizlos / unauffällig'],
}

SEKUNDAERVERBAND_GT_MAPPING = {
    # Schema-Standardwerte & Synonyme
    "Schaumstoffverbände (Foam)": ["Schaumstoffverbände (Foam)"],
    "Schaumstoffverbände": ["Schaumstoffverbände (Foam)"],
    "Schaumverband": ["Schaumstoffverbände (Foam)"],
    "PU-Schaumverband": ["Schaumstoffverbände (Foam)"],
    "dünner PU-Schaumverband": ["Schaumstoffverbände (Foam)"],
    "atraumatische Schaumverbände": ["Schaumstoffverbände (Foam)"],
    "saugfähiger Schaumverband": ["Schaumstoffverbände (Foam)"],
    "atraumatischer Schaumverband": ["Schaumstoffverbände (Foam)"],
    "absorbierender Schaumverband": ["Schaumstoffverbände (Foam)"],
    "Superabsorber": ["Superabsorber"],
    "Superabsorber-Verband": ["Superabsorber"],
    "stark saugfähige Superabsorber": ["Superabsorber"],
    "Superabsorber bei stärkerer Sekretion": ["Superabsorber"],
    "Fixiervlies / -pflaster": ["Fixiervlies / -pflaster"],
    "Elastische Fixierbinden": ["Elastische Fixierbinden"],
    "Fixierbinden / kohäsive Binden": ["Fixierbinden / kohäsive Binden"],
    "Nicht erforderlich (selbsthaftender Primärverband)": ["Kein Sekundärverband erforderlich"],

    # Kombinationsverbände (ohne künstliches Fixiervlies)
    "saugfähiger Schaumverband, atraumatische Fixierung": ["Schaumstoffverbände (Foam)"],
    "absorbierender Schaumverband, atraumatische Fixierung": ["Schaumstoffverbände (Foam)"],
    "atraumatische Schaumverbände, ggf. Unterdrucktherapie (VAC) nach Débridement": ["Schaumstoffverbände (Foam)"],
    "PU-Schaumverband, Atraumatische Fixierung": ["Schaumstoffverbände (Foam)"],
    "weicher PU-Schaumverband, weicher PU-Schaumverband": ["Schaumstoffverbände (Foam)"],
    "Elastische Fixierbinden, dünner PU-Schaumverband": ["Schaumstoffverbände (Foam)", "Elastische Fixierbinden"],

    # → Superabsorber, Schaumstoffverbände
    "Superabsorber, hochabsorbierender PU-Schaumverband": ["Superabsorber", "Schaumstoffverbände (Foam)"],
    "Superabsorber oder PU-Schaumverband": ["Superabsorber", "Schaumstoffverbände (Foam)"],
    "Superabsorber weicher PU-Schaumverband": ["Superabsorber", "Schaumstoffverbände (Foam)"],
    "Superabsorber, hochabsorbierende Schaumverbände": ["Superabsorber", "Schaumstoffverbände (Foam)"],
    "PU-Schaumverband oder Superabsorber": ["Superabsorber", "Schaumstoffverbände (Foam)"],

    # → Schaumstoffverbände mit Option auf Superabsorber
    "absorbierender Schaumverband, Superabsorber bei stärkerer Sekretion": ["Schaumstoffverbände (Foam)", "Superabsorber"],
    "weicher PU-Schaumverband Superabsorber bei stärkerem Exsudat": ["Schaumstoffverbände (Foam)", "Superabsorber"],
    "PU-Schaumverband oder Superabsorber bei stärkerer Exsudation": ["Schaumstoffverbände (Foam)", "Superabsorber"],
    "PU-Schaumverband, bei stärkerem Exsudat: Superabsorber": ["Schaumstoffverbände (Foam)", "Superabsorber"],
    "PU-Schaumverband oder kleiner Superabsorber bei stärkerer Sekretion": ["Schaumstoffverbände (Foam)", "Superabsorber"],
    "PU-Schaumverband, Superabsorber bei stärkerer Sekretion": ["Schaumstoffverbände (Foam)", "Superabsorber"],
    "kleiner PU-Schaumverband oder weicher Superabsorber bei stärkerer Exsudation": ["Schaumstoffverbände (Foam)", "Superabsorber"],
    "Superabsorber ergänzen": ["Superabsorber"],

    # → Schaumstoffverbände, sterile Polsterung / Saugkompressen
    "Sterile Saugkompressen / Polsterung": ["Sterile Saugkompressen / Polsterung"],
    "weicher PU-Schaumverband,absorbierende sterile Sekundärauflagen": ["Schaumstoffverbände (Foam)", "Sterile Saugkompressen / Polsterung"],
    "silikonisierter Schaumverband, absorbierende sterile Auflagen": ["Schaumstoffverbände (Foam)", "Sterile Saugkompressen / Polsterung"],
    "weicher absorbierender Schaumverband sterile Saugkompressen": ["Schaumstoffverbände (Foam)", "Sterile Saugkompressen / Polsterung"],
    "weicher PU-Schaumverband, sterile Polsterung": ["Schaumstoffverbände (Foam)", "Sterile Saugkompressen / Polsterung"],
    "silikonisierter Schaumverband, absorbierender PU-Schaumverband": ["Schaumstoffverbände (Foam)"],
    "weicher PU-Schaumverband, druckentlastende Polsterung": ["Schaumstoffverbände (Foam)"],
    "weicher PU-Schaumverband druckreduzierende Polsterung": ["Schaumstoffverbände (Foam)"],
    "weicher PU-Schaumverband, druckreduzierende Polsterung, ggf. Superabsorber": ["Schaumstoffverbände (Foam)", "Superabsorber"],

    # → Kompressionstherapie & Druckentlastung
    "Sekundär: Superabsorber + Fixier-/Kompressionssystem": ["Superabsorber"],
    "abhängig von der Kompressionstherapie": ["abhängig von Kompressionstherapie"],
    "abhängig von Kompressionstherapie": ["abhängig von Kompressionstherapie"],
    "über Kompression": ["abhängig von Kompressionstherapie"],
    "Kompressionstherapie": ["abhängig von Kompressionstherapie"],
    "kommt auf die Kompression an": ["abhängig von Kompressionstherapie"],
    "abhängig von Druckentlastung": ["abhängig von Druckentlastung"],
    "abhängig von der Druckentlastung": ["abhängig von Druckentlastung"],
}

PRODUKT_GT_MAPPING = {
    # Schema-Standardwerte & Schreibweisen
    "Schaumstoffverbände (Foam)": ["Schaumstoffverbände (Foam)"],
    "Schaumstoffverbände": ["Schaumstoffverbände (Foam)"],
    "Hydrofaser / Hydrofiber": ["Hydrofaser / Hydrofiber"],
    "Alginate": ["Alginate"],
    "Hydrogele (Kompresse)": ["Hydrogele (Kompresse)"],
    "Hydrokolloide": ["Hydrokolloide"],
    "Superabsorber": ["Superabsorber"],
    "Wundkontaktschichten (Silikon/Paraffin)": ["Wundkontaktschichten (Silikon/Paraffin)"],
    "Lipidokolloid-Auflagen": ["Wundkontaktschichten (Silikon/Paraffin)"],
    "Hydropolymerverbände": ["Schaumstoffverbände (Foam)"],

    # Silber entfernt → Basisklasse (gemäß Evaluierungsregel)
    "Silberhydrofaser": ["Hydrofaser / Hydrofiber"],
    "Silberalginat": ["Alginate"],
    "Silber-Schaumverbände": ["Schaumstoffverbände (Foam)"],
    "antimikrobielle Alginate": ["Alginate"],
    "Hydrofaser / Hydrofiber, silberhaltige Varianten bei bakterieller Belastung": ["Hydrofaser / Hydrofiber"],
    "Hydrofaser / Hydrofiber, Wundkontaktschichten (Silikon/Paraffin), Bei bakterieller Belastung: silberhaltige Varianten kurzfristig": ["Hydrofaser / Hydrofiber", "Wundkontaktschichten (Silikon/Paraffin)"],
    "Alginate, Hydrofaser / Hydrofiber, bei kritischer Kolonisation silberhaltige Varianten erwägen": ["Hydrofaser / Hydrofiber", "Alginate"],
    "Hydrofaser / Hydrofiber, Schaumstoffverbände (Foam), Silber-Schaumverbände": ["Hydrofaser / Hydrofiber", "Schaumstoffverbände (Foam)"],
    "Hydrofaser / Hydrofiber, Bei Infektionsverdacht silberhaltige Varianten, Schaumstoffverbände (Foam)": ["Hydrofaser / Hydrofiber", "Schaumstoffverbände (Foam)"],
    "Schaumstoffverbände (Foam), silberhaltige Verbrennungsauflagen": ["Schaumstoffverbände (Foam)"],
    "antiseptische Wundauflagen --> Silber PHMB-haltige Produkte": ["PHMB-haltige Wundauflagen"],

    "Silberhydrofaser oder Silberalginat": ["Hydrofaser / Hydrofiber", "Alginate"],
    "Silberalginate, Silberhydrofaser": ["Hydrofaser / Hydrofiber", "Alginate"],
    "Silberhydrofaser, Silberalginat": ["Hydrofaser / Hydrofiber", "Alginate"],
    "Silberhydrofaser, antimikrobielle Alginate": ["Hydrofaser / Hydrofiber", "Alginate"],
    "silberhydrofaser/Silberalginat bei kritischer Kolonisation": ["Hydrofaser / Hydrofiber", "Alginate"],
    "Silberalginat, antimikrobielle Alginate ggf. PHMB-haltige Wundauflagen": ["Alginate", "PHMB-haltige Wundauflagen"],
    "Bei feuchten/infizierten Bereichen: Silberhydrofaser Silberalginat antimikrobielle Wundauflagen.": ["Hydrofaser / Hydrofiber", "Alginate"],
    "Bei feuchten/infizierten Bereichen: Silberhydrofaser Silberalginat antimikrobielle Wundauflagen": ["Hydrofaser / Hydrofiber", "Alginate"],
    "Bei kritischer Kolonisation: Silberhydrofaser kurzfristig, Hydrogele (Kompresse)": ["Hydrofaser / Hydrofiber", "Hydrogele (Kompresse)"],
    "Bei kritischer Kolonisation: Silberhydrofaser kurzfristig": ["Hydrofaser / Hydrofiber"],
    "Alginate bei stärker exsudierend": ["Alginate"],
    "ggf. Hydrogel bei trockeneren Belägen": ["Hydrogele (Kompresse)"],
    "Alginate, Hydrofaser / Hydrofiber, Superabsorber, ggf. Unterdrucktherapie (NPWT/VAC) nach Nekrosensanierung": ["Alginate", "Hydrofaser / Hydrofiber", "Superabsorber"],

    # PHMB
    "PHMB-haltige Auflagen": ["PHMB-haltige Wundauflagen"],
    "PHMB-haltige Wundauflagen": ["PHMB-haltige Wundauflagen"],
    "antimikrobielle Alginate ggf. PHMB-haltige Wundauflagen": ["Alginate", "PHMB-haltige Wundauflagen"],

    # Trockene-Nekrose-Schutzverbände normalisiert
    "trockene sterile Schutzverbände, atraumatische Kontaktlagen, keine aggressive Befeuchtung der stabilen Nekrose": ["trockene sterile Schutzverbände", "Wundkontaktschichten (Silikon/Paraffin)"],
    "Bei trockener Nekrose: trockener Schutzverband atraumatische Kontaktlagen.": ["trockene sterile Schutzverbände", "Wundkontaktschichten (Silikon/Paraffin)"],
    "Bei trockenen Nekrosen: atraumatische trockene Schutzverbände": ["trockene sterile Schutzverbände"],
    "trockene sterile Abdeckung, atraumatische Schutzverbände, keine aggressive Befeuchtung": ["trockene sterile Schutzverbände"],
    "Bei trockenen Nekrosen: atraumatische trockene Schutzverbände, Bei feuchten/infizierten Bereichen: Silberhydrofaser Silberalginat antimikrobielle Wundauflagen": ["trockene sterile Schutzverbände", "Hydrofaser / Hydrofiber", "Alginate"],

    # Wundtyp-abhängig → Produkte behalten
    "Hydrogel bei trockenen Nekroseanteilen, Hydrofaser oder Alginat bei Exsudat": ["Hydrogele (Kompresse)", "Hydrofaser / Hydrofiber", "Alginate"],
}

DEBRIDEMENT_GT_MAPPING = {
    # Schema-Standardwerte (Katalog)
    "Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)"],
    "Mechanisch (Monofilament-Pad, feuchte Kompressen, Wundspülung)": ["Mechanisch (Monofilament-Pad, feuchte Kompressen, Wundspülung)"],
    "Chirurgisch/Scharf (Skalpell, Kürette)": ["Chirurgisch/Scharf (Skalpell, Kürette)"],
    "Enzymatisch (Kollagenase)": ["Enzymatisch (Kollagenase)"],
    "Kein Débridement erforderlich": ["Kein Débridement erforderlich"],

    # Äquivalente Phrasen & Kombinationen
    "Autolytisch (Hydrogele, Hydrokolloide, Folienverbände), vorsichtige mechanische Reinigung lockerer Beläge": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)", "Mechanisch (Monofilament-Pad, feuchte Kompressen, Wundspülung)"],
    "Autolytisch (Hydrogele, Hydrokolloide, Folienverbände), vorsichtig mechanisches Debridement": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)", "Mechanisch (Monofilament-Pad, feuchte Kompressen, Wundspülung)"],
    "vorsichtig mechanisches Debridement": ["Mechanisch (Monofilament-Pad, feuchte Kompressen, Wundspülung)"],
    "vorsichtige mechanische Reinigung lockerer Beläge": ["Mechanisch (Monofilament-Pad, feuchte Kompressen, Wundspülung)"],
    "nicht aggressiv entfernen, solange keine Revaskularisation erfolgt ist, Chirurgisch/Scharf (Skalpell, Kürette)": ["Chirurgisch/Scharf (Skalpell, Kürette)"],
    "Autolytisch (Hydrogele, Hydrokolloide, Folienverbände), chirurgisches Debridement erst nach Perfusionsverbesserung, sofern möglich": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)", "Chirurgisch/Scharf (Skalpell, Kürette)"],
    "chirurgisches Debridement erst nach Perfusionsverbesserung, sofern möglich": ["Chirurgisch/Scharf (Skalpell, Kürette)"],
    "Chirurgisch/Scharf (Skalpell, Kürette), autolytisches Debridement, enzymatisches Debridement - ergänzend": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)", "Chirurgisch/Scharf (Skalpell, Kürette)", "Enzymatisch (Kollagenase)"],
    "autolytisches Debridement, enzymatisches Debridement - ergänzend": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)", "Enzymatisch (Kollagenase)"],
    "konservatives Abwarten bei unklarer Demarkation, selektives chirurgisches Débridement, enzymatisch/autolytisch ergänzend": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)", "Chirurgisch/Scharf (Skalpell, Kürette)", "Enzymatisch (Kollagenase)"],
    "kein aggressives Debridement ohne Gefäßstatus, trockene stabile Nekrosen ggf. belassen, Bei infizierten/fibrinösen Belägen: zurückhaltendes scharfes Debridement, autolytische Verfahren möglich": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)", "Chirurgisch/Scharf (Skalpell, Kürette)"],

    "Autolytisch (Hydrogele, Folienverbände), Hydrokolloide": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)"],
    "Autolytisch (Hydrogele, Folienverbände), Hydrokolloide, Mechanisch (Monofilament-Pad, Wundspülung), feuchte Kompressen": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)", "Mechanisch (Monofilament-Pad, feuchte Kompressen, Wundspülung)"],
    "Autolytisch (Hydrogele, Chirurgisch/Scharf (Skalpell, Folienverbände), Hydrokolloide, Kürette), Mechanisch (Monofilament-Pad, Wundspülung), feuchte Kompressen": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)", "Mechanisch (Monofilament-Pad, feuchte Kompressen, Wundspülung)", "Chirurgisch/Scharf (Skalpell, Kürette)"],
    "Chirurgisch/Scharf (Skalpell, Kürette), Mechanisch (Monofilament-Pad, Wundspülung), feuchte Kompressen": ["Mechanisch (Monofilament-Pad, feuchte Kompressen, Wundspülung)", "Chirurgisch/Scharf (Skalpell, Kürette)"],
    "Autolytisch (Hydrogele, Hydrokolloide, Folienverbände), Chirurgisch/Scharf (Skalpell, Kürette), Enzymatisch": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)", "Chirurgisch/Scharf (Skalpell, Kürette)", "Enzymatisch (Kollagenase)"],
    "Mechanisch (Monofilament-Pad, Wundspülung), feuchte Kompressen": ["Mechanisch (Monofilament-Pad, feuchte Kompressen, Wundspülung)"],
    "Autolytisch (Hydrogele, Chirurgisch/Scharf (Skalpell, Folienverbände), Hydrokolloide, Kürette)": ["Autolytisch (Hydrogele, Hydrokolloide, Folienverbände)", "Chirurgisch/Scharf (Skalpell, Kürette)"],
}

SPUELLOESUNG_GT_MAPPING = {
    # Schema-Standardwerte & Katalog-Strings
    "Neutrale Spüllösung (NaCl 0,9 % / Ringer-Lösung)": ["Neutrale Spüllösung (NaCl 0,9 % / Ringer-Lösung)"],
    "Antimikrobielle Spüllösung (PHMB / Octenidin / Hypochlorit)": ["Antimikrobielle Spüllösung (PHMB / Octenidin / Hypochlorit)"],
    "Neutrale Spüllösung (NaCl, Ringer)": ["Neutrale Spüllösung (NaCl 0,9 % / Ringer-Lösung)"],
    "Antimikrobielle Spüllösung (PHMB, Octenisept)": ["Antimikrobielle Spüllösung (PHMB / Octenidin / Hypochlorit)"],

    # Synonyme & Phrasen
    "PHMB oder Octenidin zeitlich begrenzt": ["Antimikrobielle Spüllösung (PHMB / Octenidin / Hypochlorit)"],
    "Bei kritischer Kolonisation: PHMB oder Octenidin zeitlich begrenzt": ["Antimikrobielle Spüllösung (PHMB / Octenidin / Hypochlorit)"],
    "bei kritischer Kolonisation: PHMB oder Octenidin zeitlich begrenzt": ["Antimikrobielle Spüllösung (PHMB / Octenidin / Hypochlorit)"],
    "bei kritischer Kolonisation: PHMB/Octenidin": ["Antimikrobielle Spüllösung (PHMB / Octenidin / Hypochlorit)"],
    "bei kritischer Kolonisation: mit PHMB/Octenidin": ["Antimikrobielle Spüllösung (PHMB / Octenidin / Hypochlorit)"],
    "Antiseptika nur gezielt bei: Infektionszeichen, kritischer Kolonisation": ["Antimikrobielle Spüllösung (PHMB / Octenidin / Hypochlorit)"],
}

ANTIMIKROBIELL_GT_MAPPING = {
    # Schema-Standardwerte & Schreibweisen
    "Silber (Ag⁺)": ["Silber (Ag+)"],
    "Silber (Ag+)": ["Silber (Ag+)"],
    "PHMB": ["PHMB"],
    "Octenidin": ["Octenidin"],
    "Cadexomer-Iod": ["Cadexomer-Iod"],
    "Honig (Medihoney)": ["Honig (Medihoney)"],
}

HAUTSCHUTZ_GT_MAPPING = {
    # Schema-Standardwerte
    "Hautschutzfilm / Barrierespray": ["Hautschutzfilm / Barrierespray"],
    "Zinksalbe / Zinkpaste": ["Zinksalbe / Zinkpaste"],
    "Wundrandschutzpaste": ["Wundrandschutzpaste"],
    "Nicht erforderlich": ["Kein Hautschutz erforderlich"],
}

KOMPRESSION_GT_MAPPING = {
    # Schema-Standardwerte
    "Mehrkomponentensysteme (2-/4-Lagen)": ["Mehrkomponentensysteme (2-/4-Lagen)"],
    "Kurzzugbinden": ["Kurzzugbinden"],
    "Adaptive Kompressionsbandagen (Wrap)": ["Adaptive Kompressionsbandagen (Wrap)"],
    "Medizinische Kompressionsstrümpfe (MKS)": ["Medizinische Kompressionsstrümpfe (MKS)"],
    "medizinische Kompressionssysteme": ["Medizinische Kompressionsstrümpfe (MKS)"],
}

LOKALISATION_KEYWORDS = {
    "Fuß": ["fuß", "fus", "ferse", "knöchel", "zehe", "spann", "sohle", "plantar", "vorfuß", "mittelfuß",
            "fußrücken", "sprunggelenk", "malleolar", "malleol", "dorsolateral", "dorsalseitig", "rückfuß",
            "großzehe", "calcaneus", "außenknöchel"],
    "Bein": ["bein", "schenkel", "wade", "knie", "achilles", "knöchelregion",
             "unterschenkel", "gaiter"],
    "Arm": ["arm", "oberarm", "unterarm"],
    "Hand": ["hand", "handgelenk"],
    "Abdomen": ["abdomen", "bauch", "bauchdecke", "abdominal"],
    "Gesäß/Steiß": ["gesäß", "gesaess", "sakral", "steiß", "steiss", "perianal", "sakrogluteal",
                    "gluteal", "intergluteal", "leiste", "leistenregion", "inguinal"],
}

